### ISSUE TITLE
How to get the full evaluation list of each environment 

### ISSUE THREAD

**Issue by Lukeeeeee** [openai/gym#1010]
Like https://gym.openai.com/evaluations/eval_aqTWbALwQEKrLIyU9ZzmLw/ this one, is there any list of each environments's evaluation since most of environments' page did show the evaluation results like this :https://gym.openai.com/envs/Reacher-v2/ .

Also, when it said

> Reacher-v1 is considered "solved" when the agent obtains an average reward of at least -3.75 over 100 consecutive episodes.

"Average reward" here means the mean of cumulative rewards(sum  of  one step reward within one episode) over 100 episodes?

Thanks!.

**Comment by teostoleru** [comment]
@Lukeeeeee the only thing I could find is this comment where they compare v1 and v2 environments: https://github.com/openai/gym/pull/834

**Comment by christopherhesse** [comment]
I believe this information is located here https://github.com/openai/gym/blob/master/gym/envs/__init__.py#L10 in the code, though it only exists for some environments and is not as relevant since we don't run the scoreboard anymore.

I think you're correct, this should mean that you take all the rewards in each episode, sum them together, and then calculate the per-episode average over 100 episodes.
