### ISSUE TITLE
Box2d won't find some RAND_LIMIT_swigconstant

### ISSUE THREAD

**Issue by Omegastick** [openai/gym#1015]
As far as I'm aware, #100 isn't fixed, but is still closed. This has been acknowledged a couple of times in that issue but isn't being reopened for some reason.

A workaround is to uninstall box2d-kengz (`pip uninstall box2d-kengz`) then install [pybox2d](https://github.com/pybox2d/pybox2d).

Can we get pybox2d as a dependency for gym perhaps?

**Comment by brtknr** [comment]
i also have this issue

**Comment by aransena** [comment]
Just to pitch in as I haven't seen this particular error/solution noted previously, I've just had this same issue and found it was due to missing a package that would cause an error during Box2D installation, but not stop the installation process.

First uninstall Box2D
`pip uninstall Box2D`

If you try reinstall with pip install Box2D, and see this launchpadlib error
`launchpadlib 1.10.3 requires testresources, which is not installed.`

Uninstall Box2D again, and then install testresources
`pip install testresources`

Then finally resintall Box2D, hopefully now your code runs.
`pip install Box2D`

**Comment by DuaneNielsen** [comment]
Yeah, I just hit this same issue on gym.__version__ 0.10.5.  In fact, Box2D did not correctly install as a dependency of gym, then when manually installed, it borks with this "rand_int" error.  Perhaps Box2D was not the best design choice?  Maybe it should be replaced with something more reliable?

**Comment by alexp9982** [comment]
Thank you so much aransena, you have fixed my problem!

**Comment by avilay** [comment]
## Install [pybox2d](https://github.com/pybox2d/pybox2d) (not available on pypi) instead of Box2D

Hit this issue on Debian 9. Had swig 3.0.10 (this is the one that is installed by default upon running)
```
sudo apt install swig
```

My issue was that I was installing a Python package called Box2D. But when I uninstalled Box2D and installed pybox2d (https://github.com/pybox2d/pybox2d) everything started to work. Note, pybox2d is not available on pypi, so you have to install it following the instructions in INSTALL.md in the github repo. But here it is for your convenience:

#### Download the repo
    wget https://github.com/pybox2d/pybox2d/archive/master.zip

#### Unzip the source
    unzip master.zip

#### Change directory to the unzipped directory
    cd pybox2d-master

#### Build Box2D
This is the original Box2D C++ package found here (https://box2d.org/) and does not own the Python package Box2D. 

    python3 setup.py build

Ignore all warnings it shows.

#### Install pybox2d
    python3 setup.py install

Depending on python3 installation, you might have to run the last command with a `sudo`.

**Comment by christopherhesse** [comment]
This should be fixed with `box2d-py` (not `pybox2d`) that we now use in setup.py, please file a new issue if that is not the case: https://github.com/openai/gym/blob/master/setup.py#L11

**Comment by Kamier1** [comment]
> Thank you so much ！
pip install --user box2d-py==2.3.5
