### ISSUE TITLE
States in FrozenLake-v0

### ISSUE THREAD

**Issue by FranciscoGomez90** [openai/gym#1044]
Hi,

I'm learning how Reinforcement Learning works, and I have a question about this environment.
There are 16 states, a state for each cell of the 4x4 grid.
But, what are the correspondences? 
I mean, the state 0 is the grid(0,0)? 
The state 1 is the grid(0,1)? or is it the grid(1,0)??
How can I find which state describes which cell?

Thank you!

**Comment by wei-lin-liao** [comment]
Emvironment state :
" 0 , 1 , 2 , 3 ",
" 4 , 5 , 6 , 7 ",
" 8 , 9 ,10,11",
"12,13,14,15",
corresponding to 
"SFFF",
"FHFH",
"FFFH",
"HFFG"
Because default setting of environment is "slippery", agent won't move in the direction you intend.
You can observe the state by setting [ "is_slippery" : False ] before you create environment.
Tutorial is here : [https://github.com/openai/gym/issues/565](url)

**Comment by FranciscoGomez90** [comment]
Hey! Many thanks Wei!
Now I know why it doesn't move as intended to! All makes sense because of the "is_slippery" flag.
Thank you again!
