### ISSUE TITLE
Doubts

### ISSUE THREAD

**Issue by mirraaj** [openai/gym#1078]
https://github.com/openai/gym/blob/5404b39d06f72012f562ec41f60734bd4b5ceb4b/gym/envs/registration.py#L28

Can somebody please let me know what exactly ```nondeterministic``` does?

**Comment by vBarbaros** [comment]
@mirraaj - `nondeterministic` means that for the same input `A` you are not guaranteed to get the same output `B`; check the definition of the NFAs, for example, https://en.wikipedia.org/wiki/Nondeterministic_finite_automaton

**Comment by mimoralea** [comment]
What I think that line is saying is if the `nondeterministic` flag is set don't expect the same next states and rewards even if you seed the environment because the environment is "non-deterministic even after seeding". That is, the internal process of the environment is stochastic and might not return consistent next state, and rewards, whether you seed it or not.

**Comment by christopherhesse** [comment]
Thanks for answering @mimoralea, I believe you are correct.
