### ISSUE TITLE
Is there a way to know the location of the agent? (i.e. the pixel/euclidean position of the paddle in Pong)?

### ISSUE THREAD

**Issue by aznshodan** [openai/gym#1110]

**Comment by nflu** [comment]
I don't think there is an easy way to access this because the env uses the ALE which just runs bytecode from the original Atari games. You can check it out [here](https://github.com/openai/atari-py).

I'm thinking of making a tool to produce lower level state conditions for popular Atari games from pixels but I'm quite busy at the moment so this probably won't be done for at least a few weeks.

**Comment by daggertye** [comment]
It's possible to train a simple CNN to extract the paddle location, but this requires a bit of model-based rl stuff. 

Levine et al showed this [here](https://arxiv.org/pdf/1504.00702.pdf) on a more difficult task.

**Comment by nflu** [comment]
Hmm I think you are talking about two different things here.

You could certainly train a CNN to extract paddle location with supervised learning, but I think that would be overkill. For one thing you want this tool to be as quick as possible if it is used during training of your RL agent (I presume that is the use case) and CNN computation would be unnecessarily expensive.

Additionally the paddle only moves in one dimension and the pixels are white when it is there and black otherwise so you could just make a program that takes in the column of pixel values where the paddle is and by looking at which are black and which are white determine where the paddle is. This would require less computation than a CNN so it would be quicker, would require no training and also would be 100% accurate. There's a bit of a subtlety that the ball is also white but the ball is thinner than the paddle so this could look for a certain number of uninterrupted white pixels.

While I haven't read that paper, this wouldn't be a task for reinforcement learning. The tool takes in pixels and outputs the location of the paddle. There is no reward signal and there is no interaction between the tool's output and the next state of the system that generates the data.

I think something even simpler would be looking at the RAM of the simulated Atari system because the paddle location is likely stored there. I recently learned that there are versions of Atari environments that [give the RAM as observation](https://gym.openai.com/envs/Pong-ram-v0/) and also I looked into it some more and the [ALE accesses the RAM](https://github.com/openai/atari-py/blob/master/atari_py/ale_interface/src/games/supported/Pong.cpp#L36) to determine the score so you could probably adapt that to find the paddle location.

Either of those approaches would work well I think.

**Comment by Ricocotam** [comment]
As @nflu said is quite easy to get those. Actually, you can just use 2 convolution to know the location of both paddles and the ball. Build a kernel for your convolution that the exact shape for the ball and the paddles. For the ball, just convolve the image and find where's the match (only one if you build your conv well. Might not detect when on the line though). For the paddles you just need to know which one is yours as you'll detect 2 of them. Pretty simple to code (just the kernels to hand write) and super fast.

**Comment by christopherhesse** [comment]
I think @nflu answered this pretty well, this was also asked in https://github.com/openai/gym/issues/1289

**Comment by indrasweb** [comment]
```python
ram = env.unwrapped._get_ram()  # get emulator RAM state
cpu_score = ram[13]                       # computer/ai opponent score 
player_score = ram[14]                   # your score
cpu_paddle_y = ram[21]                 # Y coordinate of computer paddle
player_paddle_y = ram[51]             # Y coordinate of your paddle
ball_x = ram[49]                              # X coordinate of ball
ball_y = ram[54]                              # Y coordinate of ball
 ```

**Comment by nmerrill67** [comment]
@indrasweb How did you figure this out?
