### ISSUE TITLE
pytorch spaces for GPU support

### ISSUE THREAD

**Issue by juniorrojas** [openai/gym#1157]
Since pytorch and numpy syntax is very similar, especially after pytorch 0.4.0, would it be feasible to support pytorch action / state spaces? For example, something like this:

```py
import torch
import gym
action_space = gym.spaces.Box(low=0, high=1, shape=(3, 4), dtype=torch.float32)
```

Some environments are implemented in numpy, and because pytorch syntax is similar I think many of them could be ported to pytorch. In principle that would enable GPU support and the possibility of running multiple episodes in parallel on the GPU, which might get rid of some common bottlenecks like spawning different process to evaluate episodes, or copying data from the model living on the GPU and the simulation running on the CPU. Are there any caveats that might make this idea impractical or infeasible to implement in gym?

**Comment by 23pointsNorth** [comment]
My $0.05: Defining an action space and running an environment are completely different. And I suppose there isn't much bottleneck in checking whther the actions fall within the space in general. 
In order to use the GPU, the environemnt itself needs to be written to unilize it. The Atari roms are roms and as such do not have the actual source code to begin with, the robotics stuff utilizes simulators that are for now are not GPU accessible (potenntially bullet 3.0 last time I checked).

**Comment by pzhokhov** [comment]
what @23pointsNorth said :) In itself, making an environment that runs multiple copies on a GPU and returns a pytorch tensor is not that hard (although my gut feeling is that it has to be either a relatively simple environment with little branching in order for GPU to provide the speedup when multiple copies are run in parallel, or an environment where rendering takes most of the time). However, making exising atari and robotics envs run on GPU is impractical for the reasons @23pointsNorth specified. Given that we are not actively developing new environments in the gym, let me close this (@juniorrojas 
 feel free to comment more here if you are developing such a GPU environment and would like to share / ask questions)

**Comment by smorad** [comment]
Now that reinforcement learning is being used in realistic simulations, it may be time to revisit this :)
