### ISSUE TITLE
Gym compatibility with TPU

### ISSUE THREAD

**Issue by aidangomez** [openai/gym#1169]
Hey Gym Team,

So, I'm trying to figure out a nice way to do RL on TPUs, have you guys had any success with this? Using TPUEstimator seems like one route to go, the other is to manually do tpu.rewrite() and use a tf.Session like normal.

Would appreciate your insight and advice.

**Comment by pzhokhov** [comment]
@christopherhesse may have done some work on that, putting him in the loop.

**Comment by pzhokhov** [comment]
The closest work that I can think of is communicating observations over shared memory (like here: https://github.com/openai/baselines/blob/master/baselines/common/vec_env/shmem_vec_env.py; if TPU supports some kind of pinned shared memory, you can try similar approach; so that environment.step() happens in parallel with gradient computation
About the second point - could you elaborate a bit what kind of prefetching do you have in mind? There has been a lot of work on asynchronous writing in various replay buffers, see for instance https://arxiv.org/pdf/1802.01561.pdf and references therein

**Comment by pzhokhov** [comment]
closing this as inactive
