### ISSUE TITLE
Alpha Zero Algorithm

### ISSUE THREAD

**Issue by MerceaOtniel** [openai/gym#1245]
Hello,

I am wondering if there is a way to use alpha zero algorithm in gym. For example, in pong, how can i pit 2 networks(my own networks) using openai? I can see that you always play against an implemented Ai. Is this correct? Is there something i miss?

**Comment by wroscoe** [comment]
There was a version of alpha go in gym but was removed because it wasn't being maintained. 

Here's the code: https://github.com/openai/gym/blob/6af4a5b9b2755606c4e0becfe1fc876d33130526/gym/envs/board_game/go.py

Here's the commit where it was removed. There are also a few other board games there too. https://github.com/openai/gym/commit/4c460ba6c8959dd8e0a03b13a1ca817da6d4074f

**Comment by shuruiz** [comment]
I am afraid that you have to implement it by yourself. The alpha go zero paper shows the original algorithm, which is not hard to be implemented. The openai/gym does not provide such benchmark.  However, source code for some popular algorithms, like deepQnetwork code are provided in the baseline repo [https://github.com/openai/baselines/tree/master/baselines/deepq](url).  You can check that to facilitate your own work.

**Comment by christopherhesse** [comment]
Thanks for answering @shuruiz!  As @shuruiz mentioned, gym does not provide implementations of algorithms.  In addition, gym environments do not guarantee that you can save/restore them, so running AlphaZero's MCTS on them may not work :/
