### ISSUE TITLE
Adding an actuator to the first joint of Acrobot

### ISSUE THREAD

**Issue by StefBrands** [openai/gym#1290]
I'm trying to make both joints in Acrobot-v1 actuated instead of just the middle one in an effort to create a double pendulum balancing task. 
https://github.com/openai/gym/blob/master/gym/envs/classic_control/acrobot.py
Looking at `acrobot.py` the pendulum does not seem to be created directly there. Maybe it is in the `rk4` method but if so it is obscure.

Are there any pointers towards doing this?

**Comment by christopherhesse** [comment]
That is a bit hard to read, but I suspect you need to change https://github.com/openai/gym/blob/master/gym/envs/classic_control/acrobot.py#L171 to apply the action `a` to `dtheta1` instead of `dtheta2`.  Alternatively you could make your own Box2D environment using `box2d-py` and may be much easier to setup and debug.
