### ISSUE TITLE
Start CartPole-v1 with pendulum oriented downwards

### ISSUE THREAD

**Issue by ferreirafabio** [openai/gym#1317]
Hi,

I was wondering what the best way is to initialize the CartPole-v1 environment with a pendulum oriented downwards.

Thank you

**Comment by christopherhesse** [comment]
You should probably try editing https://github.com/openai/gym/blob/master/gym/envs/classic_control/cartpole.py but you'll also have to change the done condition since you would immediately lose if the pole was facing down.  You may want to consider the pendulum environment instead: https://gym.openai.com/envs/Pendulum-v0/
