### ISSUE TITLE
question in reacher.py

### ISSUE THREAD

**Issue by mz3718** [openai/gym#1332]
def step(self, a):
        vec = self.get_body_com("fingertip")-self.get_body_com("target")
        reward_dist = - np.linalg.norm(vec)
        reward_ctrl = - np.square(a).sum()
        reward = reward_dist + reward_ctrl
        self.do_simulation(a, self.frame_skip)
        ob = self._get_obs()
        done = False
return ob, reward, done, dict(reward_dist=reward_dist, reward_ctrl=reward_ctrl)

In the step function, the done is always assigned as False, but the step function gives True result, what's the problem? In addition, when I input in random actions, it is strange that the done is True when the target is not reached. Can anybody help with this? Thank you very much!!!

**Comment by christopherhesse** [comment]
Looks like `max_episode_steps` is set in https://github.com/openai/gym/blob/master/gym/envs/__init__.py#L209 which sets `spec.max_episode_steps` here https://github.com/openai/gym/blob/812c46cbadfffedd5ee024379ff9d7a5673ff474/gym/envs/registration.py#L64 which means `timestep_limit` is not None here https://github.com/openai/gym/blob/812c46cbadfffedd5ee024379ff9d7a5673ff474/gym/envs/registration.py#L98 which causes `gym.make` to attach a `TimeLimit` wrapper here https://github.com/openai/gym/blob/812c46cbadfffedd5ee024379ff9d7a5673ff474/gym/envs/registration.py#L130

So the reason is that there's a `TimeLimit` wrapper https://github.com/openai/gym/blob/812c46cbadfffedd5ee024379ff9d7a5673ff474/gym/wrappers/time_limit.py#L4 on your environment and after 50 steps it will say it's done because you're out of time.
