### ISSUE TITLE
How to generate random frozen lake?

### ISSUE THREAD

**Issue by cs-me** [openai/gym#1364]
Hi, 
Can someone help me with using the new facility of generating a random frozen map? Sorry if the question is trivial.

**Comment by ishan00** [comment]
FrozenLake already supports random maps. If you look at this file https://github.com/openai/gym/blob/master/gym/envs/toy_text/frozen_lake.py

You will see that the function `generate_random_map(size,p)` creates a valid map of `size * size`. In order to use it see the `__init__` function and pass proper parameters to get a new map. In your case you can pass `map_name=None` to get a `8*8` map. If you want a custom size then modify the init function that also takes the size of map as input

**Comment by cs-me** [comment]
Hi Ishan,

Thanks for the reply. I followed your suggestion and make the map_name=None in kwargs in register. But it is saying that either provide desc or map_name, both can't be none.

**Comment by cs-me** [comment]
Hi thank you so much for the reply. It worked!
