### ISSUE TITLE
Discrepancy in MuJoCo Humanoid environment

### ISSUE THREAD

**Issue by Mayankm96** [openai/gym#1380]
In the two different implementations of the MuJoCo Humanoid environment, there is a discrepancy between the computation of the forward motion reward. 

In [`humanoid_v3`](https://github.com/openai/gym/blob/master/gym/envs/mujoco/humanoid_v3.py#L107), it is implemented as: 
```python
def step(self, action):
        xy_position_before = mass_center(self.model, self.sim)
        self.do_simulation(action, self.frame_skip)
        xy_position_after = mass_center(self.model, self.sim)

        xy_velocity = (xy_position_after - xy_position_before) / self.dt
        x_velocity, y_velocity = xy_velocity

        x_velocity = ((xy_position_after[0] - xy_position_before[0])
                      / self.model.opt.timestep)
...
        forward_reward = self._forward_reward_weight * x_velocity
...
```

in [`humanoid`](https://github.com/openai/gym/blob/master/gym/envs/mujoco/humanoid.py#L30), it is calculated as:
```python
def step(self, action):
        pos_before = mass_center(self.model, self.sim)
        self.do_simulation(a, self.frame_skip)
        pos_after = mass_center(self.model, self.sim)
...
        lin_vel_cost = 0.25 * (pos_after - pos_before) / self.model.opt.timestep
...
```

Further in other MuJoCo environments, the forward motion reward is computed by dividing the difference with `dt` (which is `model.opt.timestep * frame_skip`). However, in humanoid, it is computed differently (In both the environments the `frame_skip = 5`).

I would appreciate if some clarification can be provided on this. Thank you!

**Comment by christopherhesse** [comment]
@matthiasplappert any idea why these are different?

**Comment by matthiasplappert** [comment]
No idea; seems like this was changed in https://github.com/openai/gym/pull/1304? So presumably @pzhokhov has more context on this.

**Comment by Mayankm96** [comment]
Actually, I looked again at `Humanoid_v3` and there the `forward_reward_weight` is set to 0.25 which makes the calculation of the reward term same in the two implementations. However, dividing the term by `self.model.opt.timestep` (instead of `self.dt`) is still a question.

**Comment by pzhokhov** [comment]
Aha, so I believe there are several things that are going on.
1) the v3 environments were explicitly designed to produce the same results (when initialized by default) as v2, and there is a unit test to that extent (https://github.com/openai/gym/blob/master/gym/envs/tests/test_mujoco_v2_to_v3_conversion.py)
2) division by self.dt makes more sense for velocity computation, in my opinion - the logic is really as follows: run simulator for N=frameskip steps, take the difference in positions before and after, divide by step size * N - that would give average velocity. In contrast, dividing by self.model.opt.timestep will give average velocity * N. 
3) the results between v2 and v3 match because in the v3 code `x_velocity` is actually computed in the old way (dividing by model timestep) - @Mayankm96  see the code you quoted above:
```
x_velocity = ((xy_position_after[0] - xy_position_before[0])
                      / self.model.opt.timestep)
        forward_reward = self._forward_reward_weight * x_velocity
```
Now, the fact that x_velocity and xy_velocity[0] differ by a `frameskip` factor is admittedly not great. I suppose we can change that and set default forward_reward_weight to be 0.25 / self.frameskip (this should give the same default behaviour). @Mayankm96 feel free to shoot us a PR, but otherwise, I think this can be closed.

**Comment by Mayankm96** [comment]
Yeah sure. I have sent a PR for this. I am closing the issue now. 

Thank you for your help!
