### ISSUE TITLE
Site display for algorithm status

### ISSUE THREAD

**Issue by JKCooper2** [openai/gym#151]
Now the Evaluations page has been replaced with the Algorithms page there isn't the ability to sort submissions by reviewed and writeup in order to see what needs replicating. 

It may be simpler to have some symbols display beside the algorithm name on the Algorithms page indicating the status.

The first space would be either a writeup symbol or areviewed symbol (seeing as you can't have it reviewed without a writeup), the second space could indicate replicated, meaning the user has already replicated that algorithm

**Comment by jietang** [comment]
Yes I agree it would be nice to support the replication use case better. We're experimenting with the submission model right now (for example we show all submissions on the environment page now instead of privileging hand-reviewed submissions) and figuring out how that will look probably needs to be done before we tackle this.
