### ISSUE TITLE
Support wrapper transformations to VecEnv

### ISSUE THREAD

**Issue by zuoxingdong** [openai/gym#1560]
@tristandeleu @pzhokhov @christopherhesse It might be rather convenient for the user experience to provide a list of wrapper transformations for the atomic environments when creating vectorized environment, e.g.

```python
transforms = [AtariPreprocessing, SignReward, ...]
env = gym.vector.make('Pong-v0', 16, True, transforms=transforms)
```
For additional arguments, the user is required to use `partial()` to define them within the transform list. So that each internal environment is wrapped according to the transformation list.

**Comment by tristandeleu** [comment]
I have no strong opinion against having an option to add wrappers in `gym.vector.make`. I'd leave that up to @pzhokhov and @christopherhesse. Regarding naming, we just have to keep in mind that every argument added to `make` is one that cannot be overwritten (as part of `**kwargs`) for the environment; there is already `num_envs` and `asynchronous` that cannot be overwritten.

For anything complex, I would encourage users to use `AsyncVectorEnv` (or `SyncVectorEnv`) directly, with their own custom `env_fns` functions.

**Comment by christopherhesse** [comment]
I'd rather avoid adding wrappers directly in `gym.make`, we often just provide our own `env_fn` functions as @tristandeleu indicated.  I think maybe it should be more obvious how to avoid using `gym.make` since often you'll want to apply wrappers and such almost immediately.  The same is true of `gym.vector.make` which should probably only be used for really basic cases.
