### ISSUE TITLE
CarRace is always rendered

### ISSUE THREAD

**Issue by raul-mdelfin** [openai/gym#1643]
I have tried to run CarRace-v0 without rendering the environment, but it's always rendered and this slows down each run. I have tried:

env_name = 'CarRacing-v0'
env_wrapped = gym.make(env_name)
env = wrappers.Monitor(env_wrapped, folder, video_callable=False ,force=True)

But it's still always visible.
Is there a way to run it always in the background?
(Running in macOs Sierra)

**Comment by christopherhesse** [comment]
It's possible to create a hidden window and do the rendering there, but the code does not do that currently.  Rendering is required in all cases because this env renders the screen to give it to the agent (since the agent operates on pixels instead of game state).  It probably won't affect the speed of the runs though, since there will still be a window (which is necessary for this opengl-based rendering in the absence of EGL).  Closing this in favor of https://github.com/openai/gym/issues/347
