### ISSUE TITLE
Black observation(flickering) in AirRaid

### ISSUE THREAD

**Issue by gamkkk** [openai/gym#1650]
I got many black observation(flickering) in AirRaidDeterministic-v4 shown below (same issue in [#378](https://github.com/openai/gym/issues/378)).
![flickering](https://user-images.githubusercontent.com/27881796/63008487-b23dc600-bebd-11e9-8cf0-fceebbc345b5.jpg)

However, there is no flicker in [this gameplay example](https://www.youtube.com/watch?v=QfqgNDvp70E).
Is this correct or bug??

I'm using the gym version '0.12.1' in macOS Mojave.

**Comment by christopherhesse** [comment]
This happens without using gym, so it looks like an issue with https://github.com/mgbellemare/Arcade-Learning-Environment

```
import matplotlib.pyplot as plt
import atari_py

ale = atari_py.ALEInterface()
ale.setFloat("repeat_action_probability".encode("utf-8"), 0.0)
game_path = atari_py.get_game_path("air_raid")
ale.loadROM(game_path)
ale.reset_game()
for i in range(200):
    print("i", i)
    ale.act(0)
    obs = ale.getScreenRGB2()
    plt.subplot(10, 20, i + 1)
    plt.axis("off")
    plt.imshow(obs)
    if ale.game_over():
        break
plt.show()
```

Oddly, gym-retro doesn't have black screens but does have some grayscale screens and flickering.  The current version of stella from the website: https://stella-emu.github.io/downloads.html does not seem to have these issues so it's likely these graphical issues were fixed in newer versions of stella.

Thanks for reporting this bug, but please file it on the ALE repo instead of the gym one.
