### ISSUE TITLE
How to write `step` methods for environments with actions that have fixed step sizes?

### ISSUE THREAD

**Issue by ThisIsIsaac** [openai/gym#1657]
## A little background

I am trying to add traffic light controlling environment to gym. The problem is a single action spans multiple steps (ex. green light spans 15 steps, yellow light 4 steps ...). However, `step` method of an environment must perform a single step in order to comply with `gym`'s API.

## question

How do you recommend dealing with such environments?

Some solutions I have thought of are:

1. have `step` perform multiple steps for a single action (ex. if a green light spand for 15 steps, and my agent selects green light phase, then a single call to `step` would actually run 15 steps). Then, `step` would return the number of steps it performed as well as the 4 other usual return items.

2. `step` performs a single action, but we have a loop outside of `step` s.t. the loop iterates through `step` multiple times. psudocode:

```python
action = agent.act(state)

accumulated_reward = 0
if action == "greenLight":
    for i in range(green_light_span):
        reward, state, _, _ = env.step(action)
        accumulated_reward+=reward

if action == "yellowLight":
    # iterate through `env.step` yellow_light_span number of times
    
```

Let me know what you think.

**Comment by christopherhesse** [comment]
You can wrap your environment however you want.  `AtariEnv` actually does multiple steps on the underlying environment per call of `.step()`: https://github.com/openai/gym/blob/567c620b723cd7455d4e590b9698b85dc93dc612/gym/envs/atari/atari_env.py#L119

You should probably return the number of steps taken in the `info` dict rather than as an additional return value, but besides that either of your solutions sound fine.
