### ISSUE TITLE
Image difference wrapper

### ISSUE THREAD

**Issue by maystroh** [openai/gym#1688]
I just wanted to ask if you plan to implement a frame difference wrapper, like the frame stacking one. It computes the difference between the current and previous frames. Recent papers discuss the success of such input to improve the performance of a RL agent. (here is one [reference](https://arxiv.org/abs/1901.03162))

Something along lines:

```
class DifferenceWrapper(Wrapper):
    def __init__(self, env):
        super.__init__(env)
        
        self.last_observation = None
    
    def reset(self, **kwargs):
        obs = self.env.reset(**kwargs)
        self.last_observation = obs
        return obs
    
    def step(self, action):
        obs, reward, done, info = self.env.step(action)
        
        diff_obs = obs - self.last_observation
        self.last_observation = obs
        
        return diff_obs
```

Thanks again for your help.

**Comment by christopherhesse** [comment]
@zuoxingdong seems the most interested in wrappers, any thoughts?

**Comment by zuoxingdong** [comment]
Hi @maystroh @christopherhesse , I just quickly went through the paper that you referred to, it seems that could be a standard wrapper, particularly for pixel-based / DQN-family algorithms. 

A few points I'd like to discuss here:
- This might make most sense for image observations ? If so, perhaps a name like `FrameDifference` (in consistent with `FrameStack` for "semantic similarity") could be nice
- If I understand it correctly, shall we take the absolute value for the subtraction ? Just to enforce the value range within `[0, 255]` avoiding negative values. 
- Let's discuss a bit here to make sure the generality of this functionality. Because gym should officially support a wrapper only if it is generically useful for many SOTA algorithms instead of the minor ones. Also, does it ever make sense to make API more general like letting user to decide the lag of past observation to subtract with current observation, e.g. subtract by previous observation, or previous `n`-observation.

**Comment by maystroh** [comment]
@zuoxingdong Thanks for your reply.

- `FrameDifference` would be definitely better 
- It makes sense to compute the absolute value of the subtraction
- It might be interesting to implement such behavior but, IMHO, there should be some limitations on the value of `n` to avoid memory problems (I imagine keeping more and more frames in the memory would produce problems) .. for instance restrict `n` to be between 1 and 20 (`1<n<20`).

**Comment by jkterry1** [comment]
So we aren't going to include this as a native wrapper; please use the transform obs wrapper for this
