### ISSUE TITLE
Denser reward for hand manipulate environment?

### ISSUE THREAD

**Issue by xinleipan** [openai/gym#1741]
Is there a denser reward version for the hand manipulate environments?

**Comment by pzhokhov** [comment]
yes, all the hand manipulate environments come with dense reward counterparts. You can either create them by name (i.e. `HandManipulateBlockDense-v0` instead of `HandManipulateBlock-v0`, or via gym.make kwarg `reward_type='dense'` (i.e.  `gym.make('HandManipulateBlock-v0', reward_type='dense')`.  Dense version of the reward is based on rotational and translational distances from the goal.
