### ISSUE TITLE
reward is 1.0 even though we're done

### ISSUE THREAD

**Issue by Golbstein** [openai/gym#1749]
```
state = env.reset()
done = False

while not done:
    new_state, reward, done, _ = env.step(0)
    
print(done, reward)
new_state, reward, done, _ = env.step(0)
print(done, reward)
```

it prints

> True 1.0
> True 0.0

although I assume it has to print reward=0 with done=True
>

**Comment by pzhokhov** [comment]
there is no contradiction, the last reward of the episode can be non-zero (for instance, when the episode ends with winning the game and generating positive reward).  One way to think about it is that reward is actually associated with transitions between the states, rather than with the states themselves. 
The result of second print statement in your snippet, however, is not well-defined (because the environment is being stepped after returning done).
