### ISSUE TITLE
Why is reward function of pendulum-v0 neglecting sign of angle?

### ISSUE THREAD

**Issue by tessavdheiden** [openai/gym#1801]
Hi!

Currently the reward function for pendulum-v0 is:
`-(theta^2 + 0.1*theta_dt^2 + 0.001*action^2)`

The signs of theta, theta_dt and action are not considered. If the angle < 0 and torque > 0 reward should be better than angle < 0 and torque < 0. 

So is this reward function with absolute theta, theta_d and action, ea. `(^2),` correct?

**Comment by christopherhesse** [comment]
Yeah it looks like the signs are not being considered, a more well-shaped reward would do what you're saying I think.

I don't see any paper reference for this environment, so I don't know why this particular reward function was chosen, and I doubt it's worth changing at this point because we would need to make a new pendulum-v1 environment for a new reward function.
