### ISSUE TITLE
PyBullet not functioning in Gym

### ISSUE THREAD

**Issue by tmulc18** [openai/gym#1807]
The documentation reads as if you install PyBullet, you do not need to install `mujoco-py`: "As an alternative to `mujoco-py`, consider PyBullet which uses the open source Bullet physics engine and has no license requirement."  However, this is certainly not the case during installation (i.e., `pip install gym[all]` will fail due to a `mujoco-py` dependency not being met; further, there is not an install option for robotics that is PyBullet friendly).  Finally, after looking through the robotics [source code](https://github.com/openai/gym/blob/master/gym/envs/robotics), it appears that gym does not yet support PyBullet (e.g., see [this](https://github.com/openai/gym/blob/master/gym/envs/robotics/robot_env.py#L10) line).  It seems that either this feature needs to be added or the documentation needs to be adjusted.

**Comment by christopherhesse** [comment]
It seems like the documentation is misleading.  You can use pybullet for the pybullet environments (some of which are very similar to the mujoco ones) or you can use mujoco for the mujoco-py based environments (which includes the robotics environments).

Unfortunately you can't replace mujoco-py directly with pybullet because they don't behave exactly the same.  I would welcome a PR to fix the documentation though, sorry for the confusion!

**Comment by tmulc18** [comment]
Thanks for the info!  I'll familiarize myself with the code a bit more, create the PR, and reference this issue.
