### ISSUE TITLE
Should deepcopies of envs copy the instance spec?

### ISSUE THREAD

**Issue by DiegoAE** [openai/gym#1863]
I was trying to (deep) copy gym environments and noticed a seemingly inconsistent behavior regarding the instance specification (EnvSpec). For one of the classic envs (Pendulum-v0') the spec is copied over whereas for one of the MuJoCo envs (HalfCheetah-v2) this is not the case.

```shell
>>> import gym
>>> from copy import deepcopy
>>> e1 = gym.make('Pendulum-v0')
>>> e2 = gym.make('HalfCheetah-v2')
>>> c1 = deepcopy(e1)
>>> c2 = deepcopy(e2)
>>> c1
<TimeLimit<PendulumEnv<Pendulum-v0>>>
>>> c2
<TimeLimit<HalfCheetahEnv instance>>
>>> c1.spec
EnvSpec(Pendulum-v0)
>>> c2.spec
>>> 
```
Python version: 3.6.8
OpenAI Gym version: 0.15.6

**Comment by christopherhesse** [comment]
That's weird, it could have something to do with the "EzPickle" class that mujoco envs use: https://github.com/openai/gym/blob/a6bbc269cf86b12778206d6ddda7097510e1328d/gym/envs/mujoco/half_cheetah.py#L5

**Comment by Howuhh** [comment]
How can this be fixed? I observe a similar problem, but with BipedalWalker-v2 env when using joblib.Parallel (which probably uses deepcopy). It's not comfortable, because I have to process this case separately from other envs (for example spec._env_name will raise an AttributeError).

Example:
```python
>>> import gym
>>> from copy import deepcopy
>>> env = gym.make("BipedalWalker-v2")
>>> env.spec
EnvSpec(BipedalWalker-v2)
>>> deepcopy(env).spec
>>>
```
Python version: 3.7.4
OpenAI Gym version: 0.15.4

**Comment by geyang** [comment]
@christopherhesse  do you need contributors to make a PR on this? 

Maybe @Howuhh @DiegoAE and I can try to work on a PR together

**Comment by RedTachyon** [comment]
To what extent is this actually an important feature? I think it's probably better that deepcopy copies the spec, but I'd also put this very low on the priority list, since `deepcopy`ing a gym environment isn't something that should be relied on to work. The canonical way to create multiple copies of the same environment in different processes is having each process call its own constructor.

Also worth adding that from what I'm seeing now, this does seem to be an issue only for MuJoCo and Box2D environments, since e.g. Cartpole works without issues. So considering that both of these frameworks are intended to be phased out Soon™, imo it's not worth putting a lot of effort in this.
