### ISSUE TITLE
VectorEnvWrapper is broken

### ISSUE THREAD

**Issue by jgehring** [openai/gym#1896]
The wrapper class for `VectorEnv`, introduced in #1633, does not work as expected. In contrast to the standard `Wrapper` class, it does not route function calls to the wrapped environment but relies on implementing a custom `__getattr__()` member instead. However, `VectorEnvWrapper` inherits from `VectorEnv`, and so there's no need to look up API functions like `step()` via `__getattr__` -- instead, the methods defined in the base class will be called.

The problem can be illustrated as follows:
```py
>>> import gym
>>> from gym.vector import AsyncVectorEnv
>>> from gym.vector.vector_env import VectorEnvWrapper
>>> env = VectorEnvWrapper(AsyncVectorEnv([lambda: gym.make('HalfCheetah-v2') for _ in range(3)]))
>>> env.reset()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/envs/gym/lib/python3.7/site-packages/gym/vector/vector_env.py", line 60, in reset
    return self.reset_wait()
  File "/opt/anaconda3/envs/gym/lib/python3.7/site-packages/gym/vector/vector_env.py", line 49, in reset_wait
    raise NotImplementedError()
NotImplementedError
```

The wrapper functions that would need to be defined for `VectorEnvWrapper` to work were present in the initial version of #1633 but were then removed in favor of simply using `__getattr__()`.

`VectorEnv` introduces several new abstract functions that need to be implemented by inheriting classes, and one could argue that those should be explicitly wrapped in `VectorEnvWrapper` as well, e.g. if you'd want to just override `step_wait()`. On the other hand, these functions are intended to be "private", it might be best to remove `VectorEnvWrapper` entirely and to simply use the basic `Wrapper` class instead.

**Comment by christopherhesse** [comment]
Good catch, thanks for filing the issue @jgehring!

@pzhokhov it looks like since `__getattr__()` is only called if the property is missing, it's not being activated here since the methods are not missing on the base class.  The two most obvious options are:

1) Define all methods like how it's done in the original wrapper class: https://github.com/openai/gym/blob/master/gym/core.py#L226
2) Remove VectorEnvWrapper

The second option seems tough since you may want to create wrappers, and the existing `Wrapper` class won't work if you want to override `reset_wait` for instance.

What do you think we should do here?

**Comment by pzhokhov** [comment]
https://github.com/openai/gym/pull/1917

**Comment by jgehring** [comment]
Thanks for the fix, @pzhokhov! The remaining issue I can see from overriding all functions in the wrapper like this is that you have to be aware of the semantics of `VectorEnv`'s `_async` and `_wait` methods in order to override them correctly. Essentially, if you override any of the `_step` and `_wait` functions, you need to override `step`/`reset` as well. For example, overriding `reset_wait()` only won't work because `self.env.reset()` will be called from the wrapper base class, which in turn will call `self.reset_wait()` with `self` being the wrapped env.

This could be avoided by copying the `VectorEnv` implementations of `step()` and `reset()` into `VectorEnvWrapper`, but this creates another dependency between the two classes :/

**Comment by pzhokhov** [comment]
Thanks @jgehring , that's a very good point... I agree, copying `step` and `reset` does not seem particularly elegant. To fix your particular example, we could actually remove "reset" method from the VectorEnvWrapper. This way, reset will be forwarded to the base VectorEnv class (instead of the env itself); which will call `self.reset_async()`... That also seems somewhat brittle at a glance, so let me make a unit test, and feel free to poke holes in it (i.e. add test cases that fail).

**Comment by pzhokhov** [comment]
https://github.com/openai/gym/pull/1917/commits/ff4ddb3284e0d371b23ad13a53eb33b2402e592d

**Comment by pzhokhov** [comment]
should be fixed here: https://github.com/openai/gym/pull/1917
