### ISSUE TITLE
Easy question about env.action_space.shape[-1]

### ISSUE THREAD

**Issue by DFanny-5** [openai/gym#1968]
Hi, I am just new to the openAI. I have an easy question but i can not find the answer online and I do not know where to find the document.

what does the env.action_space.shape[-1] means? What is the return value of it means.

I know that the env.action_space.shape[0] will return the number of the actions aviliable in the action space.

Does it means env.action_space.shape[n], will return the n-th action? Such as an action among turn left, turn right, go forward or go back?

If my description is unclear, please let me know.

Many thanks.

**Comment by christopherhesse** [comment]
I think shape is just a tuple of the dimensions of the action space.  Can you provide an example of which action space you are asking about?

**Comment by DFanny-5** [comment]
> I think shape is just a tuple of the dimensions of the action space. Can you provide an example of which action space you are asking about?

Hi, thanks for your help.
I found this problem when I tried to analysis the code. I found this 
nb_actions = env.action_space.shape[-1]

This nb_action is used later to create the Neural network so I really whant to figure out what exactly it represents.

Many thanks,

**Comment by christopherhesse** [comment]
Well, if the shape is just something like `(2,)` then the number of actions would be 2 since this gets the last element of the tuple.  That shape is just the shape of a `numpy.ndarray` that you'd pass in as the action, which is a tuple of ints.  You can add some `print()` statements to your code to get more information about what's actually happening there.
