### ISSUE TITLE
x-axis on gym.openai.com shows weird values like 99.995

### ISSUE THREAD

**Issue by RafaelCosman** [openai/gym#213]
E.g. https://gym.openai.com/evaluations/eval_UFV16qbdTraYLs9HnKomQ

**Comment by JKCooper2** [comment]
This comes from the x value being the mean of the edges of the bin (total eps/100), However it seems to use the total eps - 1 in calcating the mean so it sets it incorrectly.

From what I can tell it should just be a case of having `x = np.ceil(running_mean(binned.bin_edges, 2))` rather than `x = running_mean(binned.bin_edges, 2)` on line 140 of [scoring.py](https://github.com/openai/gym/blob/master/gym/scoreboard/scoring.py)

**Comment by JKCooper2** [comment]
However that code would need to be server side as I don't think it's calculated locally
