### ISSUE TITLE
Pendulum-v0 Equations 

### ISSUE THREAD

**Issue by Psarhadi** [openai/gym#2156]
Three questions in the implementation of the dynamics for the Pendulum model (can be, issues):

1- Why:  sin(th + np.pi) in line 55:

newthdot = thdot + (-3 * g / (2 * l) * np.sin(th + np.pi) + 3. / (m * l ** 2) * u) * dt

While in the dynamics equation of Pendulum-v0, it is: sin(th); 

2- why adding 3/2? It seems the equation should be (or maybe it is not a simple Pendulum):

newthdot = thdot + (-g / l * np.sin(th) + 1/ (m * l ) * u) * dt

3- Shouldn't line 54 and 55 be replaced?

53: newthdot = thdot + (-3 * g / (2 * l) * np.sin(th + np.pi) + 3. / (m * l ** 2) * u) * dt
54: newth = th + newthdot * dt
55: newthdot = np.clip(newthdot, -self.max_speed, self.max_speed)

It seems newthdot should be clipped before using in newth! Otherwise, the clip has not been applied to be integrated in the theta equation! Unless the aim is just to consider it in the reward not in the equations for theta!

**Comment by RedTachyon** [comment]
@Psarhadi 
Time to put that physics degree to use.

Ad 1 - in the dynamics it's actually -sin(π + θ) which happens to be equal to sin(π) (the minus is hidden with the 3). Theta in this environment is measured clockwise from the positive Y axis, so the angle between the radius vector and the gravitational force vector is exactly π - θ, and sin(π - θ) = sin(π).

After some more thoughts: in fact this could be made a bit clearer, since we have -sin(π + θ) = sin(π - θ) = sin(π). So in essence, changing the `-3` to `3` and `np.sin(th + np.pi)` to `np.sin(th)` won't change the dynamics, but would simplify the math a tiny bit (and I guess you'd save like two flops per step).


Ad 2 - the pendulum isn't a point mass but a rod with uniformly distributed mass, which gives a moment of inertia of \frac{m l^3}{3}, with the torque it adds up to what's implemented.

Ad 3 - I guess this depends on the intention of the original author. I agree it would make a tiny bit more sense to have the clipping performed before the integration, but in the end it's just a mechanism to stabilize the learning. I'm pretty sure the difference in practice is negligible, so it's probably not worth bumping the version for it imo. 

@jkterry1 tl;dr there are two potential changes
1 - a small (like removing 9 characters total) rewrite of the math to make it simpler without changing the actual results
3 - clipping the acceleration before applying it to the system, which would have a small (but non-zero) effect on the dynamics

I slightly lean towards implementing 1 because it simplifies the code and doesn't change the dynamics. It's not a big deal either way.

I lean moderately against implementing 2, because it would require bumping the version of the environment, and it's mostly about a design choice. The current version isn't wrong, it might just be slightly unintuitive w.r.t. the details of numerical integration of the system.

**Comment by jkterry1** [comment]
Let's do the simplification one given how heavily scrutinized this code often is.

Regarding the clipping, I'm comfortable with a version bump if it would make the behavior of the environment more expected. These environments are heavily used and reviewed and will continue to be for a long time.

**Comment by jkterry1** [comment]
Closing in favor of PR

**Comment by Psarhadi** [comment]
> @Psarhadi
> Time to put that physics degree to use.
> 
> Ad 1 - in the implementation it's actually -sin(π + θ) which happens to be equal to sin(π) (the minus is hidden with the 3). Theta in this environment is measured clockwise from the positive Y axis, so the angle between the radius vector and the gravitational force vector is exactly π - θ, and sin(π - θ) = sin(π).
> 
> After some more thoughts: in fact this could be made a bit clearer, since we have -sin(π + θ) = sin(π - θ) = sin(π). So in essence, changing the `-3` to `3` and `np.sin(th + np.pi)` to `np.sin(th)` won't change the dynamics, but would simplify the math a tiny bit (and I guess you'd save like two flops per step).
> 
> Ad 2 - the pendulum isn't a point mass but a rod with uniformly distributed mass, which gives a moment of inertia of \frac{m l^3}{3}, with the torque it adds up to what's implemented.
> 
> Ad 3 - I guess this depends on the intention of the original author. I agree it would make a tiny bit more sense to have the clipping performed before the integration, but in the end it's just a mechanism to stabilize the learning. I'm pretty sure the difference in practice is negligible, so it's probably not worth bumping the version for it imo.
> 
> @jkterry1 tl;dr there are two potential changes
> 1 - a small (like removing 9 characters total) rewrite of the math to make it simpler without changing the actual results
> 3 - clipping the acceleration before applying it to the system, which would have a small (but non-zero) effect on the dynamics
> 
> I slightly lean towards implementing 1 because it simplifies the code and doesn't change the dynamics. It's not a big deal either way.
> 
> I lean moderately against implementing 2, because it would require bumping the version of the environment, and it's mostly about a design choice. The current version isn't wrong, it might just be slightly unintuitive w.r.t. the details of numerical integration of the system.

Happy to get feedback after several months! except no:2 other changes were essential. Especially the integrator clipper was an error (with great respect). It seems to be fixed now. Thanks.
