### ISSUE TITLE
Problem with reward system in Frozen Lake, wondering how to change Frozen Lake environment configuration

### ISSUE THREAD

**Issue by DarthMalloc** [openai/gym#2181]
Based on the linked article below, the reward value at each time step should be +1.0 for reaching the goal, -0.2 for agent death, and -0.01 for reaching a non-goal frozen spot. What seems to be happening when I use the Frozen Lake environment is that at each step, the reward is +1.0 for reaching the goal and 0.0 for everything else. This poses a real problem for running experiments, and I am wondering what can be done to address this problem.
[https://ieeexplore.ieee.org/document/9144562](url)

Second, the article indicates that the Frozen Lake environment can be set to three different configurations. Please advise on how to switch between configurations.

**Comment by RedTachyon** [comment]
@DarthMalloc This article most likely uses a custom version of FrozenLake, not the one implemented here. The reward of +1 at goal, and 0 otherwise, is intended behavior. The easiest way to change it would probably be copy-pasting the implementation (https://github.com/openai/gym/blob/master/gym/envs/toy_text/frozen_lake.py) and modifying it so that the reward structure is as you want it.

As for different configurations, same story, only the first one is in gym by default. Still, if you pass a keyword argument `desc` into the environment creation, you can customize the board, like this:
```python
env = gym.make("FrozenLake-v0", desc=["SFHF", "FFFH", "FFFH", "HFFG"])
```

**Comment by RedTachyon** [comment]
@jkterry1 closable
