### ISSUE TITLE
What will happen if action passed in env.step is beyond action range?

### ISSUE THREAD

**Issue by ChenDRAG** [openai/gym#2188]
Hi,
I wonder what will happen if action passed in env.step() is beyond action range, please?
For example, in mujoco environments, will the action be ignored or replaced by some default action(do nothing action), or just automatically clip the input action to right range.

**Comment by kobinau** [comment]
The action is first clipped [here](https://github.com/openai/gym/blob/c8a659369d98706b3c98b84b80a34a832bbdc6c0/gym/envs/robotics/robot_env.py#L60)
 and then the action is scaled down [here](https://github.com/openai/gym/blob/c8a659369d98706b3c98b84b80a34a832bbdc6c0/gym/envs/robotics/fetch_env.py#L75)

this way the action won't be ignored due to the size of the input.

**Comment by ChenDRAG** [comment]
@kobinau  thanks a lot, but I see you use example from robot_env, is it the same way with all other gym envs?(e.g. mujoco)
