### ISSUE TITLE
Specific Plans for Wrapper Upgrades

### ISSUE THREAD

**Issue by jkterry1** [openai/gym#2283]
@ryannavillus is going to be overviewing gym.wrappers for the time being instead of me. I would like the following maintenance to occur:

- Include wrappers in SuperSuit that are not in Gym (per Tristian's table in #2259)
- Upgrade the transform functions to have comparable power to those in SuperSuit. I think this is very important and it's the one breaking change I think needs to happen.
- Depend on Lycon2 instead of OpenCV (described in #2259)
- Detailed code review of all current wrappers by multiple people with general improvements to code quality and comments as applicable during read review.
- ~~Detailed testing review for all current wrappers, changes to make sure tests for them are completely comprehensive
- Make sure the built in Atari preprocessing wrapper complies with current best practices (I don't believe it does), and figure out a plan if it does not (probably a new wrapper with a different name or something)~~
- Adding input tests to all wrappers with good error messages

In creating PRs for all this, stealing as much code as you want from SuperSuit is highly encouraged (with proper MIT license attribution).

Something I think is a good idea that I'm open to opinions on either way is adding versioning to wrappers the same with environments have, and the same way that SuperSuit has. I would also like to hear things people believe need to be upgraded that aren't listed here, or if there's problems with what I'm proposing.

**Comment by jkterry1** [comment]
@ryannavilus is specifically going to be reviewing all the old wrappers (except for the few giant ones, which I'll need to find someone else for for time reasons) and reviewing new wrappers people add.

**Comment by RyanNavillus** [comment]
I'm still working through reading the miscellaneous wrapper issues, but to make a few comments on this:

- We could include gym versions of certain Supersuit wrappers if they seem useful to a wide enough number of people (Gym already includes sticky actions on all v0 Atari environments, and I don't think sticky actions are used extensively outside of Atari)
- I'm not sure which specific wrappers are underpowered, or which specific features from Supersuit that you believe would be useful here, so if you could provide a list of those @jkterry1 that would help a lot.
- I think we're still figuring out who will maintain lycon2, so we'll hold off on replacing OpenCV with this for now, but I agree that this would be a good change.
- A code review of the wrappers might be worthwhile. I would like to think that if any noteworthy issues exist in the popular wrappers, there would already be a github issue for them, but that might not be the case considering how long this repository was unmaintained. I think that this should be done after we have a full plan for documentation.
- Wrapper tests would be great if we plan to make any changes. If we don't plan to modify them, then I think testing is a lower priority, since they've been field-tested quite a bit. That being said, if any bugs are found during code review, we should implement regression tests. 
- The Atari preprocessing seems to be up to date. It closely follows the recommendations of the ["Revisiting the ALE"](https://arxiv.org/pdf/1709.06009.pdf) paper, which to the best of my knowledge is the most recent, agreed-upon standard for ALE preprocessing.
- Input tests and error messages are always good, and this could be done alongside the code review and documentation.

Ultimately I think most of the obvious improvements should wait until we have a plan for documentation. We could potentially start on things like adding Supersuit functionality now if we agree on a plan for that.
