### ISSUE TITLE
Add deprecation notices for v0/v4 versions of the Atari environments and eventually remove them

### ISSUE THREAD

**Issue by jkterry1** [openai/gym#2407]
In the next release we need to add deprecation notices when importing all the v0/v4 versions of the Atari environments, in the near future (say 3 months) we should remove the v0 environments outright, and in about a year we should remove the v4 environments outright.

@JesseFarebro

**Comment by lebrice** [comment]
Hey @jkterry1 , did the atari environments get removed?
```python3
from gym.envs.atari import AtariEnv  # Doesn't work
```
And even after `pip install gym[atari]`, and using the recommended syntax from the `gym/envs/README.md`:
```python3
from gym.envs import atari  # also doesn't work
AtariEnv = atari.AtariEnv
```

**Comment by JesseFarebro** [comment]
Hi @lebrice, they have been removed from Gym. Once you install `gym[atari]` it installs the new Arcade Learning Environment python wrapper `ale-py`. You can essentially achieve the same `AtariEnv` by importing `ale_py.gym.ALGymEnv`, i.e.,

```py
from ale_py.gym import ALGymEnv
```

Just note that some of the default parameters to `ALGymEnv` have changed. See this blog post for additional info: [https://brosa.ca/blog/ale-release-v0.7](https://brosa.ca/blog/ale-release-v0.7). Furthermore, the class is now located here: https://github.com/mgbellemare/Arcade-Learning-Environment/blob/master/src/python/gym/environment.py.

**Comment by lebrice** [comment]
Thanks for the explanation @JesseFarebro. 
However, I can't help but wonder why this change was made in such a backward-incompatible way! Would you consider re-introducing the package in the `gym.envs` namespace using something like a try-except clause? I feel like this might have broken literally all the RL research code out there!

**Comment by JesseFarebro** [comment]
I don't understand what your use case is? It's not common to import the actual `AtariEnv` class. This wasn't even documented anywhere and is what I'd consider off-label. The documented method for instantiating Atari environments is to call `gym.make`, i.e.,

```py
import gym

env = gym.make('Breakout-v0')
```

This still works as intended, it just hooks into the aforementioned `ALGymEnv` class. Why would you be directly importing `AtariEnv`? All arguments that you'd pass to `AtariEnv` can be passed to `gym.make`. From what I can see on Github search this isn't commonplace and definitely won't break all RL research code, the `gym.make` paradigm is what's ubiquitous. Am I missing something here?

**Comment by lebrice** [comment]
Indeed, you're 100% correct, I retract my earlier statement! :sweat_smile:

**Comment by JesseFarebro** [comment]
@lebrice you do raise a good point though. I am seeing code that checks the `EnvSpec` entry point for `gym.envs.atari`. I think there's been a push to decouple these environments from Gym's core so other packages have been removed from `gym.envs`. Perhaps it's too late to go back? @jkterry1 thoughts?

At worst this is a one-line change for anyone using `gym >= 0.2`.

**Comment by araffin** [comment]
> In the next release we need to add deprecation notices when importing all the v0/v4 versions of the Atari environments, in the near future (say 3 months) we should remove the v0 environments outright, and in about a year we should remove the v4 environments outright.

Although I understand this would allow using latest version of the ALE, recent breaking changes including this proposed one go directly against what was discussed in https://github.com/openai/gym/issues/2259
especially (quoting @jkterry1 reply):
"Regarding "I would highly recommend you to take it slow and make careful decisions about any modification (that is not documentation or fixing typos) to avoid bloating or breaking the package." is there anything in particular you're thinking of here that I'm missing? This sounds like my expressed goal as well. The only things I intend to break are what I stated- the vector environment API, because all the RL library developers have a bunch of problems with it and recommending developers use different preprocessing wrappers."

As a result, SB3 now capped gym version otherwise users will get confusing errors when upgrading: https://github.com/DLR-RM/stable-baselines3/pull/569/commits/e7a48d29df5b1f519d8e037ac6ba91f9608cef42#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7

**Comment by JesseFarebro** [comment]
@araffin in your commit you say `gym 0.20 breaks atari-py behavior`. Can you elaborate here?

**Comment by araffin** [comment]
> @araffin in your commit you say gym 0.20 breaks atari-py behavior. Can you elaborate here?

Multiple steps are now required to install atari envs with ROMS (`pip install gym[atari]` is no longer enough) which breaks any CI or tutorial on atari games.
I assume that you will get a bunch of issues of users not able to use atari games anymore...

Side note: warnings are also emitted if ale py and atari-py are installed (saying roms are not compatible) and ale py emits a deprecation warning about `select` method

**Comment by JesseFarebro** [comment]
This isn't a new change, `atari-py` stopped distributing ROMs more than a year ago. That has nothing to do with v0.20 or `ale-py`. There's no path forward where `pip install gym[atari]` will install ROMs for you. This is part of the reason in `ale-py` I introduced the ROM plugin system. Conceivably someone could distribute ROMs which are pip installable, or you could package your own Python package for CI, or you can use something like @jkterry1's [AutoROM](https://github.com/PettingZoo-Team/AutoROM) which can install ROMs via one CLI command. This is how Gym now does its CI.

RE: warnings, those will be fixed in a minor release in the next couple of days. What will happen is we'll still emit a warning for unsupported ROMs but they will be available for use regardless of the warning.

**Comment by JesseFarebro** [comment]
@lebrice I have an elegant solution which solves all of our issues regarding `gym.envs.atari`. In `ale-py` I'll be able to use namespace packages to provide `gym/envs/atari/*` when a user installs `ale-py`. This means that the environment code can live in the ALE repository but the Gym specific environment code will be installed to its proper package @ `gym.envs.atari`.

This will make any code relying on `entry_point` backwards compatible while the ALE remains in control over the environment code. I'll post an update once I'm closer to releasing this.

**Comment by araffin** [comment]
> There's no path forward where pip install gym[atari] will install ROMs for you

pinning atari py to 0.2.5 was enough to solve the issue.

**Comment by JesseFarebro** [comment]
It's my understanding that releases of `atari-py` with ROMs will be pulled eventually. I'll inquire about the timeline of this.

**Comment by JesseFarebro** [comment]
As of `gym>=0.21` the entry point remains `gym.envs.atari:AtariEnv`, thanks @lebrice. Furthermore, see the [latest release notes](https://github.com/openai/gym/releases/tag/v0.21.0) for how to manage ROMs in `gym>=0.21`.

**Comment by kwilson-tech** [comment]
I'm not sure if this is useful, but I had issues with Atari v0 environments and ALGymEnv. When I ran my program, I did get ALGymEnv error and followed the posts stating that I should do `pip install ale-py==0.7` and `pip install gym==0.20` but I obtained this error "Error: Unable to find game "Breakout", did you import Breakout with ale-import-roms?". So, instead of using `gym==0.20` I installed `gym==0.19` and that resolved those issues both issues.

**Comment by pseudo-rnd-thoughts** [comment]
@JesseFarebro @jkterry1 Is there any progress on deprecating v0 or v4?

**Comment by araffin** [comment]
> @JesseFarebro @jkterry1 Is there any progress on deprecating v0 or v4?

i wouldn't deprecate and remove v4 before any extensive study is made, see https://github.com/DLR-RM/stable-baselines3/pull/865#issuecomment-1100236113 (if i recall, Jesse mentioned at some point that there was no intention to remove v4)

**Comment by JesseFarebro** [comment]
As @araffin said, I have no plans to outright remove `v0` or `v4` anytime soon. It would break too many existing projects. I think the work done here: https://github.com/openai/gym/pull/2535 was a good compromise for the time being, i.e., we warn users when they're using an outdated environment. Most projects who are actively using `v0` or `v4` can make a one-character change to upgrade and get rid of the warning message.

**Comment by jkterry1** [comment]
There are deprecation warnings now, the environments aren't planned to be removed outright for the foreseeable future to ensure reproducibility.
