### ISSUE TITLE
[Proposal] Adding type hints

### ISSUE THREAD

**Issue by jkterry1** [openai/gym#2452]
Per [this](https://sethmlarson.dev/blog/2021-10-18/tests-arent-enough-case-study-after-adding-types-to-urllib3) recently article, we really should work to add type hints to Gym over time. This is something that can be worried about after the major upcoming changes are planned, but none-the-less this is important for a package of Gym's scale. Incremental contributions towards this end are very welcome.

**Comment by ikamensh** [comment]
@lebrice https://docs.python.org/3/library/typing.html#typing.runtime_checkable says: `Note runtime_checkable() will check only the presence of the required methods, not their type signatures.` - this seems like a really weak guarantee for compatibility, therefore maybe not something that should be recommended to gym users. I would be for the first option you have described.

> whether it would be best to make Envs generic in terms of the types of their observations/actions, or in terms of the type of their spaces

I think they should be generic in terms of Obs / Actions types, and specify that spaces share this generic typing as in your first message. Essentially spaces like `TupleSpace` should further restrict the type they can be generic (if type system allows this), therefore one should get type error for `Env[ndarray, ndarray]` with `TupleSpace`.

**Comment by XuehaiPan** [comment]
> The `Tuple[float, float, float, float]` seems extremely unscalable, no? There are plenty of environments with significantly larger state spaces.

We can try:

```python
>>> from typing import Tuple

>>> Tuple[float, float, float, float]
typing.Tuple[float, float, float, float]

>>> Tuple[(float,) * 4]
typing.Tuple[float, float, float, float]

>>> Tuple[(float,) * 4] == Tuple[float, float, float, float]
True

>>> Tuple[(float,) * 10]
typing.Tuple[float, float, float, float, float, float, float, float, float, float]
```

I'd prefer using [`numpy.typing.NDArray`](https://numpy.org/devdocs/reference/typing.html#numpy.typing.NDArray) rather than `typing.Tuple`. Cause `gym.space.Space` usually returns a `numpy.ndarray` instead of `bultins.tuple`.

However [`numpy.typing.NDArray`](https://numpy.org/devdocs/reference/typing.html#numpy.typing.NDArray) requires `numpy >= 1.21.0`, and it do not support specifying the `shape` of the array only the `dtype`. [PEP 646 -- Variadic Generics (Python >= 3.10)](https://www.python.org/dev/peps/pep-0646).
