### ISSUE TITLE
Fix Peter Zhokov's issue with Gym dict spaces

### ISSUE THREAD

**Issue by jkterry1** [openai/gym#2476]
See last comment in https://github.com/openai/gym/pull/2446

@duburcqa

**Comment by duburcqa** [comment]
What do you mean by "Fix Peter Zhokov's issue" ? The old behavior of Gym.Dict `__contains__` has been preserved.  

I believe the assertion of @pzhokhov saying "I believe this PR may introduce subtle bugs for users" is wrong because even though I removed `__contains__` implementation, it is actually still inherited from `gym.Space` itself so it should be fine.

**Comment by vwxyzjn** [comment]
With the latest master @pzhokhov's code sample 
```
from gym import spaces
space = spaces.Dict({'a': spaces.Box(-1, 1, shape=(1,))})
sample = space.sample()
# the following assert conditions were true before
assert sample in space
assert not 'a' in space
```
seems to run without errors. So I guess @pzhokhov's last comment is already addressed...?
