### ISSUE TITLE
ModuleNotFoundError: No module named 'gym.envs.atari'

### ISSUE THREAD

**Issue by jgp-github** [openai/gym#2498]
### Question

I have installed gym[atari], but when I run ''import gym env = gym.make("Pong-v4")'', the error is coming. I want to kown how to solve it. thanks for your answer.

**Comment by JesseFarebro** [comment]
Make sure you have `ale-py` installed. Try `pip install -U gym[atari]`. You should see v0.7.3 when calling `pip show ale-py`.

**Comment by alcinos** [comment]
Hi,

I hit the same issue in a fresh environment.
The `ale-py` version seems correct:
```
$ pip show ale-py                                  
Name: ale-py
Version: 0.7.3
```
Gym version is  0.21.0 and `atari-py` is 0.2.9.  It fails for all versions of the game I tried, `v0`, `v4` and `ALE/___-v5`.

The problem went away when downgrading to `gym` 0.19.0 (which in turn downgraded `atari-py` to 0.2.9)

Happy to give any relevant info to help tracking this down.

Best

**Comment by JesseFarebro** [comment]
@alcinos what's the specific error you get when instantiating the `v0`, `v4`, and `v5` environments?  The same module not found error?

**Comment by alcinos** [comment]
@JesseFarebro yes, same `ModuleNotFoundError: No module named 'gym.envs.atari'` error

**Comment by JesseFarebro** [comment]
Can you give me more info on your setup, e.g., what version and distribution of Python are you using? What OS? Can you try uninstalling gym, ale-py, atari-py, i.e.,
```
pip uninstall gym atari-py ale-py
pip install gym[atari]
```
and see if it works after that?

**Comment by alcinos** [comment]
Hi @JesseFarebro 
Thank you for your help!

I am not sure how I managed to get a corrupt conda environment that triggers that error in the first place. I tried to reproduce again from a clean env but didn’t manage to. It’s probably a combination of 1) out-dated requirements.txt in third party repos (eg DeepMind’s Dopamine requires atari-py, which, if I understand correctly, is deprecated)  2) out-dated installation instruction floating on the web.

Anyways, the culprit is likely atari-py, thanks for pointing that out. The issue is resolved as far as I’m concerned.

As a nitpick, it would probably be helpful to have a word on rom installation in the readme of this repo, since I expect most user to install Atari environments that way (as opposed to `pip install ale-py`). Most documentation available elsewhere on the internet is outdated and encourages installing atari-py.

Thank you again for your time and your amazing support of ALE over the years.

Best

**Comment by Andrewzh112** [comment]
Created new environment, then `pip install -U gym[atari] --no-cache` then `import gym gym.make('PongNoFrameskip-v4')` will still raise the same error

**Comment by Andrewzh112** [comment]
> Can you give me more info on your setup, e.g., what version and distribution of Python are you using? What OS? Can you try uninstalling gym, ale-py, atari-py, i.e.,
> 
> ```
> pip uninstall gym atari-py ale-py
> pip install gym[atari]
> ```
> 
> and see if it works after that?

still getting the same issue: created new env, fresh reinstalled all packages. Im on Ubuntu 20.04 and python 3.8

**Comment by JesseFarebro** [comment]
@Andrewzh112 make sure you haven't installed Gym locally with the `-e` flag. Namespace packages don't work in editable mode OR when gym is on your `PYTHONPATH`, you must install Gym from PyPi, e.g., `pip install gym`.

**Comment by profversaggi** [comment]
I'm still having the same issue as articulated above but with no solution:

Ubuntu Desktop 20
Tried:
atari_py 0.2.5, 0.2.6, and 0.2.9
Gym 0.18.0 and 0.19.0


ERROR:
ModuleNotFoundError: No module named 'gym.envs.atari'

**Comment by dorinesinenco** [comment]
> 

Same here

**Comment by JesseFarebro** [comment]
@profversaggi from looking at your post in in https://github.com/PacktPublishing/Hands-On-Intelligent-Agents-with-OpenAI-Gym/issues/39 you __cannot__ run things within the Gym directory. This is exactly what I was saying here: https://github.com/openai/gym/issues/2498#issuecomment-994072778.

If you clone Gym locally it will __not work__ if you're running scripts in the local folder OR if you installed Gym with editable mode (i.e., `pip install -e`). You must install Gym using `pip` either by `pip install gym`, or `pip install .` if you've already cloned it locally.
