### ISSUE TITLE
[Bug Report] Using torch multiprocessing context in AsyncVectorEnv

### ISSUE THREAD

**Issue by GaetanLepage** [openai/gym#2501]
**Describe the bug**
When providing the multiprocessing context from pytorch, the `AsyncVectorEnv` init crashes.
More precisely, when calling Python multiprocessing `get_context` method (https://github.com/openai/gym/blob/b84b69c872a3159900e6ec82a4b98cfa3e7bb0ed/gym/vector/async_vector_env.py#L119), it fails with
```
ValueError: cannot find context for <multiprocessing.context.SpawnContext object at 0x7efd1d7c3730>
```
I manage to get it working by commenting this line and replacing it with:
```
ctx = context
```
Maybe, it should become:
```
if isinstance(context, multiprocessing.context.SpawnContext):
    ctx = context
else:
    ctx = mp.get_context(context)
```
Though, I am not 100% sure about this fix as I am not an expert on Python's management of multiprocessing.
Maybe this behavior is expected and I am using it wrongly.

**Code example**
```
environment: gym.VectorEnv = gym.vector.AsyncVectorEnv(
    env_fns=[lambda: RlanWerMapEnv(config=config.env_config)
                    for _ in range(4)],
    shared_memory=False,
    context=torch.multiprocessing.get_context('spawn')
)
```

**System Info**
gym 0.21.0 installed using `pip`.

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/openai/gym/issues) in the repo (**required**)

**Comment by tristandeleu** [comment]
The context argument in `AsyncVectorEnv` is meant to be a string, to match the `method` argument in [`multiprocessing.get_context()`](https://docs.python.org/3/library/multiprocessing.html#multiprocessing.get_context). In your example, I think you could just set `context='spawn'` instead of `context=torch.multiprocessing.get_context('spawn')`, I think PyTorch's multiprocessing contexts should be compatible with Python multiprocessing contexts.

**Comment by GaetanLepage** [comment]
Indeed @tristandeleu, it works with the `'spawn'` string alone.
I originally thought that calling `torch` was having an effect in the background...

Closing then !
