### ISSUE TITLE
mountain_car's reward problem not fixed yet?

### ISSUE THREAD

**Issue by yagshi** [openai/gym#2504]
I've read #2123, #2194, and #2009.  I agree with the conclusion of the discussion.  But, the comment in the code still says
> Reward of 0 is awarded if the agent reached the flag (position = 0.5)

I think

 1. this comment should be removed, OR
 2. some code like `reward = 0 if done else -1` should be incorporated

for just consistency.

Thank you.

**Comment by jkterry1** [comment]
You're correct that the comment was wrong, the reward logic however is not

**Comment by yagshi** [comment]
I see.  Thanks a lot!

**Comment by jkterry1** [comment]
@yagshi could you please confirm that this clarifies things for you? https://github.com/openai/gym/pull/2534/files

**Comment by GaetanLepage** [comment]
Hello,
Personally, I find it quite tricky  explained like this.
Indeed, the RL framework implies that, because the episode has ended, all future rewards will be 0 which is coherent with the fact that the `step()` function never returns 0.

If it was on me, I would explained it like this:
_During the whole episode (while the car is not at the top at the mountain), the reward given is `-1`. Hence, to maximize the cumulated reward, you want the episode the be as short as possible._
And I would not even talk about an `0` reward obtained at the end.

Maybe it is obvious for most people with the current comment, but I think it would not hurt anyone if it was even more clearly explained. I honestly don't know.
