### ISSUE TITLE
AttributeError: module 'gym' has no attribute 'undo_logger_setup'

### ISSUE THREAD

**Issue by lbq8942** [openai/gym#2505]
```
import gym
gym.undo_logger_setup()
```
what's something wrong?

**Comment by seungjaeryanlee** [comment]
This method was deprecated in 0.9.6 and removed in 0.10.8. Since 0.9.6, the logger should not be modifying the global logging configuration, so you shouldn't need to undo anything.

If you do need to call it for some reason, you can check the following code snippet.

https://github.com/openai/gym/blob/6af4a5b9b2755606c4e0becfe1fc876d33130526/gym/configuration.py#L31-L43

You can also check PR #836 that deprecated this method and PR #1154 that removed this method.

**Comment by jkterry1** [comment]
Thanks for the reply!
