### ISSUE TITLE
[Bug Report] InvalidVersionSpec: Invalid version '3.': empty version component

### ISSUE THREAD

**Issue by randolf-scholz** [openai/gym#2518]
If you are submitting a bug report, please fill in the following details and use the tag [bug].

**Describe the bug**
The requirements.txt contains the line

```
opencv-python>=3.
```

Which causes the following bug, when gym is pip installed in a `conda` environment with `pip_interop_enabled`.

```
Collecting package metadata (current_repodata.json): \ WARNING conda.core.index:push_record(267): Skipping pypi/pypi::gym-0.21.0-pypi_0 due to InvalidSpec: 3.
done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.

InvalidVersionSpec: Invalid version '3.': empty version component
```

**Code example**
Please try to provide a minimal example to reproduce the bug. Error messages and stack traces are also helpful.

```
conda create --name demo python
conda config --env --set pip_interop_enabled True
pip install gym
conda update --all
```

This can be resolved by changing the version string to 

```
opencv-python>=3.0*
```

**Comment by randolf-scholz** [comment]
I also created a bug report on conda, maybe they will fix it on their side as well https://github.com/conda/conda/issues/11097

**Comment by RedTachyon** [comment]
Hold on, is there any universe in which `>=3.` is valid versioning for a python package? I don't think conda will fix anything because there is nothing to fix on their part, it seems like a simple typo in the requirements.

That being said conda integration is mentioned in #2393, and is technically not supported right now. And in general, I think we'll need to rethink the default requirements, since opencv is pretty chonky and only needed for Atari, so absolutely shouldn't be a default dependency

Does anyone more up-to-date with opencv know whether just setting the version to >=3.0 will be good enough? @JesseFarebro maybe you know what's needed for Atari?

**Comment by randolf-scholz** [comment]
@RedTachyon I had a second look at [PEP440](https://www.python.org/dev/peps/pep-0440/) and it says

> To ensure local version identifiers can be readily incorporated as part of filenames and URLs, and to avoid formatting inconsistencies in hexadecimal hash representations, local version labels MUST be limited to the following set of permitted characters:
> 
> ASCII letters ([a-zA-Z])
> ASCII digits ([0-9])
> periods (.)
> **Local version labels MUST start and end with an ASCII letter or digit.**

So yes it seems like it is not a valid python version string.

**Comment by randolf-scholz** [comment]
@RedTachyon I checked [PEP440](https://www.python.org/dev/peps/pep-0440/) and `">=3."` does not pass the regex test from appendix B.
