### ISSUE TITLE
[Question] action space related question

### ISSUE THREAD

**Issue by zhy149** [openai/gym#2549]
### Question

If you're a beginner and have basic questions, please ask on [r/reinforcementlearning](https://www.reddit.com/r/reinforcementlearning/) or in the [RL Discord](https://discord.com/invite/xhfNqQv) (if you're new please use the beginners channel). Basic questions that are not bugs or feature requests will be closed without reply, because GitHub issues are not an appropriate venue for these.

Advanced/nontrivial questions, especially in areas where documentation is lacking, are very much welcome.

Hello, I'm doing a robotics grasping project. The action space in my environment now is discrete with 12 possible actions ranging from 0 to 11. However, for different states (images), there are different valid actions. For example, some states need to avoid collision, so only actions 1, 3, 7, 8 are valid, while for another state maybe actions 2, 3, 6, 9, 11 are valid. Is there any proper way that I can implement such restriction in my custom environment so that reinforcement learning libraries algorithms such as stable baselines and rllib can be implemented on my environment?
Thanks a lot!

**Comment by balisujohn** [comment]
As far as I know, there's no officially supported way to prevent an action being allowed at a gym level. What I would recommend is configuring your custom environment so that conditionally disallowed actions either result in the episode ending early, or result in nothing happening and a small negative reward. In the first case, as long as reward tends to be positive and the agent is not incentivized to end the episode early, the agent should learn to avoid the "illegal" actions. For the second case where "illegal" actions result in nothing happening, the agent should also learn to avoid illegal actions, especially if there is a small reward penalty. 

So stable-baselines3 will still be able to request illegal actions, but the environment will not allow them to be taken.
