### ISSUE TITLE
[Proposal] Autoreset when stepping in done state

### ISSUE THREAD

**Issue by jkterry1** [openai/gym#2564]
@JesseFarebro proposed a future which I actually think we should do- have environments automatically reset when you take an action in a terminal state, and the observation returned is the first one for each state. This would mean you only need to call reset once (though you could call if more often if desired for seeding), and is analogous to what dm_env does. I think this would result in a big quality of life improvement for users and involve very little code changes, and is standard amongst other APIs. Unless there's a huge issue here someone points out, I think this should be done.

**Comment by balisujohn** [comment]
I've been looking into this, and the big question that comes up for this feature is: "what do we do with the action being input in the .step() call which causes the reset(.step() called when done=1)"

In my current draft, the action is ignored, and the .step() fuction returns the result of a call to .reset() as well as a hard-coded zero reward and done=0. @jkterry1  Does this seems alright, or is there another behavior that would be ideal here? 

My worry is if we first reset, then apply the action, we now have two new observations from the environment and can only return one of them.

**Comment by RedTachyon** [comment]
Can this actually even be done for environments in general? I think the only realistic implementation would be through a wrapper, and adding a wrapper like this is definitely not a big deal. Whether it should be default in `gym.make` is another question.

The way I'd see it implemented is having a guard in the `step` code, after performing the step logic:

```python
if done:
    obs, info = env.reset(...)
```

and probably adding the final observation to the info dict.

I don't see why an action should ever be ignored. After you get a `done==True`, the next action goes to the next episode.

Overall I think I'm fine adding this as a wrapper, and then whether or not it will be used, is down to the user.

**Comment by balisujohn** [comment]
@RedTachyon 
A wrapper is a good idea, my original plan was to modify all the first party environments, but I think a wrapper would take less work and would be able to capture the behavior adequately.

I think the final observation in the info dict would be a bit non-straightfoward assuming people are trying to reconstruct trajectories, since adding the extra state from the last info is an extra thing to remember to do.  Also, there might already be arbitrary keys in the info dict from the environment, meaning there could be key overlap unless we use a nested info dict. 
 
So if you think it's fine to use an info dict to return the final observation, let me know if you'd prefer
 
 ```` 
info =  {env_info: {...}, final_obs: [...]}
````
or
 ```` 
 {env_info..., final_obs: [...]}
````

and I'll proceed with implementing the wrapper.

**Comment by JesseFarebro** [comment]
Indeed, my thoughts for this was a wrapper. It would look something like this:

```py
class AutoResetWrapper(gym.Wrapper):
    def __init__(self, env):
        super().__init__(env)
        self._reset_next_step = True # False?

    def reset(self, **kwargs):
        self._reset_next_step = False
        return self.env.reset(**kwargs)

    def step(self, action):
        if self._reset_next_step:
            obs, infos = self.reset(return_info=True)
            return obs, None, False, infos

        obs, reward, terminal, infos = self.env.step(action)
        self._reset_next_step = terminal
        
        return obs, reward, terminal, infos
```

Let me know if you have any other questions about this.

**Comment by jkterry1** [comment]
@balisujohn does this make more sense to you?

**Comment by balisujohn** [comment]
I submitted a PR which should be ready for review.

**Comment by RedTachyon** [comment]
I'm not really a fan of this approach. If I understand it right, it introduces one `env.step()` between episodes where the action is ignored, and the reward is `None`, which would be a pain to properly handle. It's a step that you have to treat in a special way (can't add the reward to all the previous rewards), so it might as well just be a `reset()`

I think I would much more prefer a more seamless transition - after the step in which `done=True`, the environment gets reset and the observation there would be the start of the next episode. That does make it more annoying to process the final observation (which imo should be in the info one way or another), but there probably won't be a perfect solution without a significant change to the API

**Comment by jkterry1** [comment]
@balisujohn I spoke to people on discord, and I'd actually like to do what Ariel proposed.

To explain this in more detail, the idea is that after the final action, the observation returned is that of the initial state of the environment after it's reset. The actual final observation can be included in the infos dict via a standardized spec, because it's not commonly used (it can't be used to act, it can only be used for computing value functions in certain cases). This would create a significantly cleaner API where the environment can just be arbitrarily iterated through. Does that sound reasonable?

**Comment by jkterry1** [comment]
I actually have an additional suggestion per my proposal. While I think that this feature should be enabled by default I think that, given that getting the last state is more inconvenient in contexts where you need it, we should keep this an optional feature in the 1.0 release.

**Comment by jkterry1** [comment]
My intention was to make it a wrapper that's applied to all first party envs (likely with the argument that I mentioned), and part of the API compliance test. Either way this should be encoded via wrapper.

**Comment by balisujohn** [comment]
Makes sense, sounds good!

**Comment by balisujohn** [comment]
@jkterry1 alright redone, ready for review again :^)

**Comment by JesseFarebro** [comment]
Although it might seem weird to take an "empty" action on the terminal observation the reason for this is to enable a unified API where you don't have to keep track of episode boundaries, this is especially useful for vectorized environments. For example,

```py
env = gym.vector.make('...', n=4)

obs = env.reset()
for _ in range(num_env_interactions):
    next_obs, reward, terminal, infos = env.step(get_actions(obs))
    # If you need to deal with a terminal observation what are you going to do?
    # You'd have to filter the infos PyTree by terminal
    # Instead if you take the "empty action" API you can just keep calling step()
    # and never have to worry about this.
```

If you really care about the "empty action" distinction it's much easier to handle this in agent space by doing something like:
```py
def get_action(timestep):
    if timestep.terminal:
        return NOOP
    return my_cool_agents_policy(timestep.observation)
```
, than to deal with handling the terminal observation in the infos dict. This also just doesn't make sense from an API contract standpoint, step is performing a transition, the contract is `state, action -> next_state, reward, terminal` where `(next_state, reward, terminal)` is the "transition" from the state-action pair. The only special case is if you have a terminal state the action is a NOOP as this resets the environment. I don't think we should be breaking this contract by returning an arbitrary `next_state`, this would be very confusing. It's much less confusing to think about: "if I'm in a terminal state my next action is a NOOP as this crosses episode boundaries", at least it is for me.

**Comment by RedTachyon** [comment]
> the reason for this is to enable a unified API where you don't have to keep track of episode boundaries

I'd say with the no-op method, you very much need to keep track of episode boundaries. Consider a basic loop
```python
rewards = []
for _ in range(...):
    obs, reward, done, info = env.step(...)
    rewards.append(reward)
```

With your method, this introduces a None to a list of floats, which is never a fun time. 


> This also just doesn't make sense from an API contract standpoint, step is performing a transition

The same exact problem applies to your method though? You're breaking the contract by introducing a step that does not perform an in-environment transition, and wave it away as an "only special case". In both methods it will be an only special case, the difference is what this special case will be. I don't see how one would be more confusing than the other outside of being used to either option, so any other model will be confusing.

**Comment by JesseFarebro** [comment]
> I'd say with the no-op method, you very much need to keep track of episode boundaries.

My example above was explanatory, ideally you'd return something from `step` that tells you what this transition is, intra-episode or inter-episode. Just having `reward` being `None` isn't enough. My earlier arguments are w.r.t. the user not having to act on episode boundaries if they don't need to, this includes not having the user explicitly call `reset`.

To make this more concrete: you should get back a "transition" from `step` that tells you 1) what type of transition this is, 2) what's the observation, 3) reward if there's a reward associated with the transition, 4) additional info. The advantages of this design + auto reset are:

- Unified vector & non-vector API
- No undefined behavior when calling `step` on a terminal environment
- You have a way to get the first observation without calling `reset` which can be overloaded
- The user doesn't need to deal with environment boundaries, i.e., they don't need to worry about resetting the environment

> The same exact problem applies to your method though?

No. You're just not making the valid distinction of intra-episode transition versus inter-episode transition. A valid intra-episode transition is one where `state, action -> next_state` is a valid transition from the MDP. Your proposed method violates this as `state_{T-1}, action_T -> state_0` is not a valid transition in the MDP, the environment has a valid transition, i.e., `state_{T_1}, action_T -> state_T`. Having inter-episode transitions where you go from `state_T, * -> state_0` doesn't violate this as there is no valid transitions from `state_T` to any other state, we are now defining this ourselves.

## Expressivity of `step`'s return type 

Auto-resetting is overloading the definition of a transition as I explained above. For this to make sense you need to know what type of transition you're getting from `step`. I think the real problem here is Gym's `step` return type. Why hasn't it been discussed to make it more robust and return perhaps a `NamedTuple`? You could specify whether this is an inter or intra episode transition or even "first" (reset transition), "middle" (env transition), or "last" (transition to terminal) as DM-env does. Making the return type a `NamedTuple` allows you to add extra fields and functionality and enables you to expand on this in the future. If v1.0 is going to make breaking changes this is probably one of the most important changes you could make for the future of this project IMO. How many compromises have you already made because of this design choice? I can name a few off the top of my head: `return_info` argument to `reset` and the truncation versus termination proposal.

I think @RedTachyon's fundamental concern here is with the lack of transparency to the user (correct me if I'm wrong). I somewhat agree with this. If Gym does auto-resetting by default it should probably be built-in to the API and not exist as an opaque wrapper. IMO this would involve changing the return type of `reset` and `step` to a common container that can properly  grow with the project.

**Comment by vwxyzjn** [comment]
My two cents is that if we do this wrapper it should have identical behavior as to how vector env auto resets. I'd also avoid `None` if possible...

> This also just doesn't make sense from an API contract
If this is a big issue, then wouldn't @RedTachyon's approach be clearer?
```
if done:
    obs, info = env.reset(...)
```

> To make this more concrete: you should get back a "transition" from step that tells you 1) what type of transition this is, 2) what's the observation, 3) reward if there's a reward associated with the transition, 4) additional info. The advantages of this design + auto reset are:

Sorry, I don't quite get this. Would you mind giving a specific code example?

**Comment by araffin** [comment]
> While I think that this feature should be enabled by default

The auto-reset feature is probably the most confusing concept of `VecEnv` and generates quite some issues despite an explicit warning in the doc:
- https://github.com/hill-a/stable-baselines/issues/1083
- https://github.com/DLR-RM/stable-baselines3/issues/719
- https://github.com/DLR-RM/stable-baselines3/issues/582
- https://github.com/DLR-RM/stable-baselines3/issues/460
- https://github.com/sail-sg/envpool/issues/33

So I would rather have it as an opt-in option rather than an opt-out.

> I think this would result in a big quality of life improvement for users 

Did you have already several requests by users? including beginners?

**Comment by balisujohn** [comment]
I think that's a compelling cases for making autoreset opt-in, so I'm inclined to agree

**Comment by jkterry1** [comment]
I agree. The only question now is if we leave this as a wrapper or as an argument on env creation. An argument on env creation that defaults to false is my preference, and issues with this?

**Comment by balisujohn** [comment]
So if we make this as an argument on env creation, would this mean adding an optional "autoreset" argument to gym.make, then passing the rest of the arguments to the environment constructor and wrapping the environment with the autoreset wrapper?

**Comment by jkterry1** [comment]
yes, though the wrapper wouldn't be applied by default
