### ISSUE TITLE
Doom envs create from threads leave behind running vizdoom processes

### ISSUE THREAD

**Issue by danijar** [openai/gym#257]
After some experiments that open multiple Doom environments from different threads, my X server reports this and I cannot open any more windows.

```
Maximum number of clients reached
```

There are several running `vizdoom` instances left after the agent script terminates and I have to run `killall vizdoom -9` to get my machine working again.

![vizdoom](https://cloud.githubusercontent.com/assets/2111293/17001914/51bb25d2-4ec9-11e6-9b78-86deb848585b.png)

**Comment by ppaquette** [comment]
I get the following error while trying to run Doom envs in multiple threads. 

```python
[xcb] Unknown request in queue while dequeuing
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
python2.7: ../../src/xcb_io.c:179: dequeue_pending_request: Assertion `!xcb_xlib_unknown_req_in_deq' failed.
Aborted (core dumped)
```

This probably means that the envs are not thread-safe, and that's why the vizdoom processes are not killed properly.

If I create a lock on the main thread, and request a lock before any operations, the multiple threads work perfectly, and the vizdoom processes are killed properly (but they run a bit slow)

```python
import gym
from threading import Thread, Lock

def _run_env():
    is_done = False
    actions = [0] * 43
    actions[0] = 1
    with main_lock:
        env = gym.make('DoomBasic-v0')
        env.reset()
    while not is_done:
        with main_lock:
            env.render()
            obs, reward, is_done, info = env.step(actions)
    with main_lock:
        env.close()

# Starting threads
main_lock = Lock()
for _ in range(5):
    env_thread = Thread(target=_run_env)
    env_thread.start()
```

How do you think this bug should be fixed?

**Comment by ppaquette** [comment]
Update:

The issue is caused in the render() function, which is not thread-safe.

The following code works way faster, and cleans up the vizdoom processes properly.

```python
import gym
from threading import Thread, Lock

def _run_env():
    is_done = False
    actions = [0] * 43
    actions[0] = 1
    env = gym.make('DoomBasic-v0')
    env.reset()
    count = 0
    while not is_done:
        count += 1
        if count % 10 == 0:
            with main_lock:
                env.render()
        obs, reward, is_done, info = env.step(actions)
    env.close()

# Starting threads
main_lock = Lock()
for _ in range(5):
    env_thread = Thread(target=_run_env)
    env_thread.start()
```

The proper workaround is to lock() calls to render(), or to not call render() at all.

**Comment by danijar** [comment]
@ppaquette Thanks for investigating. I run all experiments offline and don't even call `env.render()`. Are you sure that your example cleans up all vizdoom processes?

**Comment by ppaquette** [comment]
Positive. All vizdoom processes are terminated properly with the example above.

I'm not sure why your vizdoom processes are not terminating properly. It might be an error being thrown somewhere.

**Comment by danijar** [comment]
That might very well be the case. Maybe the Doom envs could use `sys.excepthook` to clean up the processes on error?

**Comment by ppaquette** [comment]
I took a deeper look. It might be one of the following:

### 1. Too many processes are started.

Processes are started with ```void DoomController::launchDoom``` in VizDoom, which is called respectively by ```bool DoomController::init()```, ```bool DoomGame::init()```, ```bool DoomGamePython::init()```,  ```DoomEnv._load_level()```,  ```DoomEnv._reset()```.

A process is started on the first .reset() call, which is expected, but not for subsequent .reset() calls, which will start a new episode in the same process. You should have one running process per thread.

### 2. Processes are not explicitly closed

Since .reset() doesn't close the process (as it may start a new episode), the ```env.close()``` needs to be called explicitly, otherwise the vizdoom process will never close. The process is actually closed within ```void DoomController::close()``` and follows the same stack trace as above.

### 3. Error in thread prevents env.close() from being called

This was the scenario I was describing previously where an error in the running thread (e.g. render()) was halting code execution in the thread, and preventing env.close() for being called, therefore leaving the vizdoom processes running.

### 4. VizDoom doesn't close the process properly

I'm doubtful of this one, but it is still a possibility.

.
Can you provide me with a short test case that replicates the bug (to better understand the code you are running), or if you prefer to have a crack at it, you can try submitting a pull request.

```sys.excepthook``` would need to be implemented on all envs (as a cleanup routine). I'm sure we can come up with something simpler to fix this issue.

**Comment by danijar** [comment]
Cool, I'll try to provide you with a minimal example. I'm busy the next days and will get to it afterwards.

**Comment by ppaquette** [comment]
Submitted PR #282 that should solve this issue.

- envs can be wrapped in 'with' clause, so they are automatically cleaned up.
- Added `lock` param to configure() to be able to handle cases where vizdoom crashes when launched across multiple processes.

Let me know what you think of it.
