### ISSUE TITLE
Creating gym style environment from real device

### ISSUE THREAD

**Issue by PeterPirog** [openai/gym#2580]
Hello

I would like to create RL controler for [temperature calibrated bath](https://isotech.co.uk/products/fluidized-furnace-model-875/) but the problem is how te create simulator for it.
RL training directly from real device  states has no sense because time of device stabilization is very very long.

action space is: 0 and 1 (heater off or on)
state: [enviroment temperature, bath temperature]
reward: abs( bath temperature - set temperature)
goal: stabilize temperature as quick as possible

I have reecorded data
 action: recorded values if heater is on or off
 state: bath temperatures 

Problem is in fact that delay betwen action and state is about 80 seconds.  I tested that device modeling as lowpas filter (inifinite impulse response IIR) works well, equation has form:

Y(n)=a1 x Y(n-1)+a2 x Y(n-2)+...+ak x Y(n-k)+b0 x X(n)+b1 x Y(n-1)+...+bk x X(n-k)

The question is: Does anybody know way to prepare easily  device simulator such type of device (lowpass filter with long delay)?
Now I try to find filter coefficients with excel solver  ut this method is not easy to modify hyperparameters of model.

**Comment by pseudo-rnd-thoughts** [comment]
Hi,

Normally in reinforcement learning, we are trying to maximise our reward over time, therefore, reward=abs(bath temperature - set temperature) would reward the agent the larger the difference in temperature. 
This can be fixed easily with reward= - abs(bath temperature - set temperature)
In addition, I would add to your state the set temperature as otherwise, the agent has no idea what is the correct temperature to change to is 
 
If you know how the environment and bath temperature will change after N seconds of the heater turned off or on then this is possible to implement as a gym environment. Is this what the Y function does? Sorry I don't understand it

**Comment by jkterry1** [comment]
I'm going to close this issue, but you guys are free to keep discussing :)

**Comment by PeterPirog** [comment]
@pseudo-rnd-thoughts , Thank you for your suggestions, of course it should be negative values to optimize reward,  and set temperature should be a part of state vector.

I consider to use [SysIdentPy](https://sysidentpy.org/) library as a core of environment simulator. Now I collected data from physical device (calibration bath) ad I try to use it.

**Comment by pseudo-rnd-thoughts** [comment]
You should be able to create an openai gym that is basically a wrapper around the SysIdentPy library. 
On reset, using some random initial value for the all of the state variables
At each time step, take a certain time step in the environment simulator (e.g., 0.5 second, 1 second, 5 second), updating the state

Do you have anymore questions?

**Comment by PeterPirog** [comment]
@pseudo-rnd-thoughts  Thank You for the suggestions, I will try it.
