### ISSUE TITLE
[Bug Report] Box bounded below and above doesn't work when dtype is int

### ISSUE THREAD

**Issue by rusu24edward** [openai/gym#2629]
**Describe the bug**
A `Box` space that is created with dtype `int` and `low` (`high`) values being `-np.inf` (`np.inf`) will return `bounded_{above,below}` as True.

**Code example**
```python3
from gym.spaces import Box
import numpy as np

unbounded_below = Box(
    np.array([0, 13, -3, -np.inf]),
    np.array([0, 20, 0, 0]),
    dtype=int
)

unbounded_above = Box(
    np.array([0, 12, 20, 0]),
    np.array([np.inf, 20, 24, np.inf]),
    dtype=int
)

print(unbounded_above.bounded_above)
print(unbounded_below.bounded_below)

>>> [ True  True  True  True]
>>> [ True  True  True  True]
```

**My analysis**
At the [broadcast](https://github.com/openai/gym/blob/master/gym/spaces/box.py#L64), [get_inf](https://github.com/openai/gym/blob/master/gym/spaces/box.py#L226) turns `np.inf` into their integer equivalents. Determining [boundedness](https://github.com/openai/gym/blob/master/gym/spaces/box.py#L86) is comparing directly with `np.inf`, not with the integer equivalents given from `get_inf`.

**System Info**
Describe the characteristic of your environment:
 * Gym installed with pip
 * MacOS 10.15.7
 * Python version: 3.7.9
 * numpy 1.21.5

**Additional context**
I know it may seem strange to use `np.inf` with an integer-Box, but I use integer-Boxes all the time, and I need to check against `np.inf`.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/openai/gym/issues) in the repo (**required**)

**Comment by RedTachyon** [comment]
I don't think this can be really easily solved in gym? The moment you write `np.array([0, 13, -3, -np.inf])` and want it to be of an integer dtype, *something* will go wrong, the question is just how it will go wrong - because you don't have an infinite int.

If your bound is an integer, it is pretty muddy whether the space is bounded or unbounded, since the bound can just happen to be the max/min integer.

#2630 fails tests, seems to be mainly due to `uint` spaces, so that would be fixable. I'm not 100% sure if that will actually resolve the issue, but you can try to fix it (and test it)

**Comment by rusu24edward** [comment]
@RedTachyon True, it is not clearly defined what would happen. I believe this issue describes some ways of "how it will go wrong". The presence of the integer type in the [`get_inf`](https://github.com/openai/gym/blob/master/gym/spaces/box.py#L181) function suggests to me that `Box` is interested in dealing with cases of "infinite" integers and provides an abstraction to do so. #2630 does fix the sample code above. I'll push forward with the test fixes.

**Comment by jkterry1** [comment]
I'm going to close this in favor of #2630 just so I can keep track of things
