### ISSUE TITLE
[Proposal] Possibility to have empty `space.Box`

### ISSUE THREAD

**Issue by thomashirtz** [openai/gym#2692]
### Proposal 

Possibility to have empty `space.Box`.

### Motivation and Pitch

I am writing a library for training agent on hybrid reinforcement learning task. And I am thinking about way to create the action space. In theory you need to give a number which is the index of the action that you want to perform and parameters. The parameters are dependent on the task that you want to perform.  

I originally tried to concatenate all the parameters into one array [(here)](https://github.com/thomashirtz/gym-hybrid/blob/6efe6c24f60157b6da4414b578536ff2103e79bd/gym_hybrid/environments.py#L101). However, I discovered that some algorithm needs to know exactly which action are related to which parameters. I therefore wanted to copy what have been done in [this](https://github.com/cycraig/gym-platform/blob/e9329879dbb62badbbef89648162c97ba1e4d837/gym_platform/envs/platform_env.py#L125) environment because I think it is the best way to do it.  
Namely having a tuple of action\_space composed of a discrete and a tuple of box space for all the different action's parameters. However because my environment has one action that doesn't have any parameters. I cannot create an empty box using gym. I don't think another good way to create action space exist for hybrid action space environment if one of the parameter space is empty.

[Link](https://github.com/thomashirtz/gym-hybrid/issues/4) to my issue. This is the "ideal" code however it errors because of the empty box:

```
import numpy as np
from gym import spaces


ACCELERATE = 0
TURN = 1
BREAK = 2

action_id_to_domain = {
    ACCELERATE: {'low': [0.], 'high': [1.]},
    TURN: {'low': [-1.], 'high': [1.]},
    BREAK: {'low': [], 'high': []},
}

action_space = spaces.Tuple(
    (
        spaces.Discrete(len(action_id_to_domain)),
        spaces.Tuple(
            tuple(
                spaces.Box(low=np.array(d['low']), high=np.array(d['high']), dtype=np.float32)
                for _, d in sorted(action_id_to_domain.items())
            )
        )
    )
)
```

A clear and concise description of what you want to happen:

Be able to create a `spaces.Box` with empty size shape

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/openai/gym/issues) in the repo (**required**)

**Comment by jkterry1** [comment]
Could you please give the specific space creation method that fails? `Box(low=0, high=1, shape=())` works

**Comment by thomashirtz** [comment]
Oh ok! I used the code from the first message, I thought I could have just initialize low and high with empty array. But now it seems quite logical that it wouldn't work
Thank you!

**Comment by thomashirtz** [comment]
I tried to use the `Box(low=0, high=1, shape=())` however when I sample it I do get a value. My issue was in case where I needed to have a Box that is just a placeholder. e.g. how to represent the action space if I have one discrete action and three actions that are continuous and one of the hybrid action is empty (no parameter for this discrete action)

**Comment by RedTachyon** [comment]
What exact behavior do you expect from an empty Box? Should `Box.empty.sample()` raise an exception?

Overall it seems to me that since the empty box is just a placeholder that won't be used, you just need to make a convention and stick to it as for the interpretation of it. For example a valid box is on with a nontrivial shape, and if the shape is `()`, then that's the empty box, because no array is contained by it. 
Or are there some specific functionalities you expect from this empty box?

Another alternative you could try is doing something like `Box(low=0, high=0, shape=(0,))`, sampling from it gives you an empty array. 

I can see some potential other deliberate implementations, but that really depends on what exactly you want as its behavior.

**Comment by RedTachyon** [comment]
@thomashirtz What exact behavior do you expect from an empty Box? Should `Box.empty.sample()` raise an exception?

Overall it seems to me that since the empty box is just a placeholder that won't be used, you just need to make a convention and stick to it as for the interpretation of it. For example a valid box is on with a nontrivial shape, and if the shape is `()`, then that's the empty box, because no array is contained by it. 
Or are there some specific functionalities you expect from this empty box?

Another alternative you could try is doing something like `Box(low=0, high=0, shape=(0,))`, sampling from it gives you an empty array. 

I can see some potential other deliberate implementations, but that really depends on what exactly you want as its behavior.

**Comment by thomashirtz** [comment]
@RedTachyon I think that the expected behavior is to be able to obtain an empty array (or None) when the Box is sampled. 

I think the main important point is that it would also be possible to access the attribute of a Box, because that would be quite annoying to not easily be able to loop through the tuple that contains all the `spaces` (In the first example, if I set `None `instead of the `break` Box, it would give attribute error when trying to get the shape or other attributes).

`Box(low=0, high=0, shape=(0,))` is raising an error unfortunately
