### ISSUE TITLE
[Bug Report] Environments where obs are RGB images giving obs of 3 dimensional numpy arrays of mostly 0s

### ISSUE THREAD

**Issue by DexiongYung** [openai/gym#2747]
If you are submitting a bug report, please fill in the following details and use the tag [bug].

**Describe the bug**
Both `obs` and `processed_obs` in the below code are giving 3 dimensional numpy arrays with mostly 0s filling it, even after transposed. It should show a car, road and background.

**Code example**
```
import gym
from gym.spaces import Box
import numpy as np
import cv2
from PIL import Image as im


def process_obs(obs): # a single frame (96, 96, 3) for CarRacing
    obs = cv2.resize(obs[:84, :, :], dsize=(64,64), interpolation=cv2.INTER_NEAREST)
    return np.transpose(obs, (2,0,1))

env = gym.make('CarRacing-v1')
env.observation_space = Box(low=0, high=255, shape=(3,64,64), dtype=env.observation_space.dtype)
action_space = env.action_space
obs = env.reset()
processed_obs = process_obs(obs)
im.fromarray(processed_obs, mode='RGB').save(f'start.png')

for i in range(3):
    random_action = env.action_space.sample()
    obs, reward, done, info = env.step(random_action)
    processed_obs = process_obs(obs)
    im.fromarray(processed_obs, mode='RGB').save(f'test_{i}.png')
````

**System Info**
Gym was installed via pip
Ubuntu 18.04
Python 3.9.12

### Checklist

- [/] I have checked that there is no similar [issue](https://github.com/openai/gym/issues) in the repo (**required**)

**Comment by Markus28** [comment]
Concerning your code, and in particular this line:
```
env.observation_space = Box(low=0, high=255, shape=(3,64,64), dtype=env.observation_space.dtype)
```
You shouldn't really alter the environment's action/observation spaces directly (because now `env`'s observations don't match `env.observation_space`!). It would be best practice to implement an [ObservationWrapper](https://www.gymlibrary.ml/content/wrappers/#observationwrapper).

Concerning your actual question: The environment should zoom into the car after a few more steps. Take a look at the animation [in the docs](https://www.gymlibrary.ml/environments/box2d/car_racing/). Can you try running a few more steps and see whether it looks fine?

**Comment by jkterry1** [comment]
Hey, I'm going to close this due to inactivity, please let us know if you need any additional help :)
