### ISSUE TITLE
[Question] No module named 'gym.envs.classic_control.rendering' .How do I fix it?

### ISSUE THREAD

**Issue by Tomoyukiryu** [openai/gym#2806]
I run a en example fro gym-retro randomagent and error message poped out saying "File "/home/.../lib/python3.7/site-packages/retro/retro_env.py", line 228, in render
    from gym.envs.classic_control.rendering import SimpleImageViewer
ModuleNotFoundError: No module named 'gym.envs.classic_control.rendering'.

**Comment by pseudo-rnd-thoughts** [comment]
So gym retro is another project by openai that I don't believe is being maintained anymore. https://github.com/openai/retro
The gym rendering API was updated from pyglet to pygame in 0.22.0 so I would guess you would need to use an old version of gym.

**Comment by Tomoyukiryu** [comment]
Thank you ,that worked.

**Comment by wookayin** [comment]
v0.21.0 has the rendering gym.envs.classic_control.rendering. Gym suddenly removed this module without no deprecation periods, in #2551.

**Comment by pickettgoogle** [comment]
I ran into the same issue with Retro.  Honest question: What is the policy gym is using for backwards compatibility?  (Generally, I thought these kinds of breaking changes were announced with much ado, such as Python2 to Python3.)

**Comment by jjshoots** [comment]
@pickettgoogle Gym 0.25 represents a very stark API change in comparison to all the releases before that. Because of that, we have pushed hard for all libraries that depend on Gym to update to the newer API, as maintaining backwards compatibility was a much larger task than the update itself. These changes were actually part of almost a year of discussions, and is very well known in the Gym realm.

Unfortunately, Retro is not maintained by us (we are not OpenAI, the organization that manages Gym is Farama Foundation, OpenAI simply cuts releases) and as such, we have no power over what happens in that realm. The best advice I can give is to either make a PR to Retro requesting them to update their API, or use an older version of Gym with Retro, along with versions of the learning libraries that are compatible.

**Comment by jkterry1** [comment]
@pickettgoogle you might want to try this instead, it's a community maintained fork of retro (though it hasn't been updated recently): https://github.com/MatPoliquin/stable-retro

Also a small typo above- the breaking changes were in 0.26 not 0.25
