### ISSUE TITLE
gym import error 

### ISSUE THREAD

**Issue by 2359181042** [openai/gym#2863]
If you are submitting a bug report, please fill in the following details and use the tag [bug].

**Describe the bug**
AttributeError: partially initialized module 'gym' has no attribute 'core' (most likely due to a circular import)

**Code example**
import gym
env = gym.make("CartPole-v1")
observation, info = env.reset(seed=42, return_info=True)

**System Info**
AttributeError                            Traceback (most recent call last)
Input In [4], in <cell line: 1>()
----> 1 import gym
      2 env = gym.make("CartPole-v1")
      3 observation, info = env.reset(seed=42, return_info=True)

File ~\anaconda3\lib\site-packages\gym\__init__.py:16, in <module>
     14 from gym import logger
     15 from gym import vector
---> 16 from gym import wrappers
     18 __all__ = ["Env", "Space", "Wrapper", "make", "spec", "register"]

File ~\anaconda3\lib\site-packages\gym\wrappers\__init__.py:17, in <module>
     15 from gym.wrappers.clip_action import ClipAction
     16 from gym.wrappers.record_episode_statistics import RecordEpisodeStatistics
---> 17 from gym.wrappers.normalize import NormalizeObservation, NormalizeReward
     18 from gym.wrappers.record_video import RecordVideo, capped_cubic_video_schedule

File ~\anaconda3\lib\site-packages\gym\wrappers\normalize.py:41, in <module>
     36     new_count = tot_count
     38     return new_mean, new_var, new_count
---> 41 class NormalizeObservation(gym.core.Wrapper):
     42     def __init__(
     43         self,
     44         env,
     45         epsilon=1e-8,
     46     ):
     47         super(NormalizeObservation, self).__init__(env)

AttributeError: partially initialized module 'gym' has no attribute 'core' (most likely due to a circular import)

Describe the characteristic of your environment:
 * Describe how Gym was installed (pip, docker, source, ...)
 * What OS/version of Linux you're using. Note that while we will accept PRs to improve Window's support, we do not officially support it.
 * Python version

**Additional context**

### Checklist

- [ ] I have checked that there is no similar [issue](https://github.com/openai/gym/issues) in the repo (**required**)

**Comment by pseudo-rnd-thoughts** [comment]
I'm not able to replicate your issue on the latest version
Could you tell us what OS, python version, gym version you are using?

**Comment by jkterry1** [comment]
Hey, I'm going to close this due to lack of activity

**Comment by wanzaixiaomantou** [comment]
AttributeError: partially initialized module 'gym' has no attribute 'core' (most likely due to a circular import)  I can't find the answer for many days, is there anybody who encountered this problem

**Comment by wanzaixiaomantou** [comment]
AttributeError: partially initialized module 'gym' has no attribute 'core' (most likely due to a circular import)  I can't find the answer for many days, is there anybody who encountered this problem

**Comment by pseudo-rnd-thoughts** [comment]
Could you provide an example script and gym version number?

**Comment by SCzhJ** [comment]
I encountered similar problem when I was following a tutorial of atari breakout on Jupyter

**Error Prompt:**
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [2], in <cell line: 1>()
----> 1 import gym
      2 from stable_baselines3 import A2C
      3 from stable_baselines3.common.vec_env import VecFrameStack

File D:\anaconda3\lib\site-packages\gym\__init__.py:16, in <module>
     14 from gym import logger
     15 from gym import vector
---> 16 from gym import wrappers
     18 __all__ = ["Env", "Space", "Wrapper", "make", "spec", "register"]

File D:\anaconda3\lib\site-packages\gym\wrappers\__init__.py:17, in <module>
     15 from gym.wrappers.clip_action import ClipAction
     16 from gym.wrappers.record_episode_statistics import RecordEpisodeStatistics
---> 17 from gym.wrappers.normalize import NormalizeObservation, NormalizeReward
     18 from gym.wrappers.record_video import RecordVideo, capped_cubic_video_schedule

File D:\anaconda3\lib\site-packages\gym\wrappers\normalize.py:41, in <module>
     36     new_count = tot_count
     38     return new_mean, new_var, new_count
---> 41 class NormalizeObservation(gym.core.Wrapper):
     42     def __init__(
     43         self,
     44         env,
     45         epsilon=1e-8,
     46     ):
     47         super(NormalizeObservation, self).__init__(env)

AttributeError: partially initialized module 'gym' has no attribute 'core' (most likely due to a circular import)

**Solution:**
I uninstalled gym and reinstalled it, and everything just work out.

**Comment by pseudo-rnd-thoughts** [comment]
What gym version are you using?

**Comment by belenda** [comment]
I have had this problem 
AttributeError: partially initialized module 'gym' has no attribute 'core' (most likely due to a circular import)
I'm using gym 0.26.2

**Comment by belenda** [comment]
> Solution:
I uninstalled gym and reinstalled it, and everything just work out.

> I've upgraded gym and it is not working. 
I'm trying to uninstall but it is taking a lot of time ...

**Comment by pseudo-rnd-thoughts** [comment]
Do you have any code to replicate this issue using a fresh install of gym

**Comment by cirosantilli** [comment]
This happens if you have a file in the current directory with the same name as an stdlib module, e.g. `random.py`: https://stackoverflow.com/questions/36250353/importing-a-library-from-or-near-a-script-with-the-same-name-raises-attribute I don't think there's anything gym can do about it, you just have to rename the file.
