### ISSUE TITLE
[Bug] env.render() giving no/wrong results

### ISSUE THREAD

**Issue by wookayin** [openai/gym#2889]
**Describe the bug**

After the merge of new render API #2671 which is not stable yet, `env.render()` giving no results when it is called more than once. Also the rendering result is not correct in terms of type and shape. Please see the example below.

**Code example**
```python
env = gym.make("HalfCheetah-v4", render_mode='rgb_array')
env.reset()
im = env.render(width=200, height=200)
im2 = env.render()
```

I see three problems here:

* `im` contains a **python list** of [480x480x3] ndarray: `im[0].shape == (480, 480, 3)`. In our early version of gym, `im` itself was a ndarray. I don't think that rendered images contained in a list is correct; and the behavior is different.

* The width/height parameter `env.render(width=200, height=200)` are ignored; the rendering dimensions are wong.

* The next call of `env.render()` will give no results: it returns an empty list, i.e. `im2 == []`

**System Info**

- gym: latest HEAD 053ee809324861dc1bec19feee97b47ba1557a94
- installed from source 
- macOS 
- python 3.10

**Additional context**

/cc @younik who is the author of #2671.

- [x] I have checked that there is no similar [issue](https://github.com/openai/gym/issues) in the repo (**required**)

**Comment by younik** [comment]
Hello,

> im contains a python list of [480x480x3] ndarray: im[0].shape == (480, 480, 3). In our early version of gym, im itself was a ndarray. I don't think that rendered images contained in a list is correct; and the behavior is different.

This is done on purpose; with the new render API, the method `render` returns a collection of frames. You can do some steps without calling render to see this. 

> The width/height parameter env.render(width=200, height=200) are ignored; the rendering dimensions are wong.

When you use the new render API, those arguments should be passed to `__init__`. Tho, you are right, they are still not implemented in `__init__`; I will push a fix soon, thanks for spotting it.
The legacy code still works with dimensions (don't specify `render_mode` to use it).

> The next call of env.render() will give no results: it returns an empty list, i.e. im2 == []
This is the expected behaviour since the `render` call pops the frames from the collection. This is done to allow user to clean the frame collection.

**Comment by wookayin** [comment]
Since this is not a bug as per #2671, I will close this issue. Let me move and continue my argument to #2671 to centralize the discussion.
