### ISSUE TITLE
[Proposal] Add an environment showcasing the Graph space

### ISSUE THREAD

**Issue by RedTachyon** [openai/gym#2912]
With #2869, we added the Graph spaces (mainly for observation spaces I'd imagine), but at the moment I'd say their support is purely theoretical. The code exists, compiles, and even passes some tests, but it's not actually used anywhere.

While we're pretty careful about adding new envs, I do think it would be valuable to add an example env that actually uses this code.

NB: the same would apply if #2908 is accepted (i.e. string/text-based spaces).

**Comment by pseudo-rnd-thoughts** [comment]
I agree, this could be done as a tutorial rather than without gym itself
@jjshoots Thoughts on an environment using the `graph` space

**Comment by jjshoots** [comment]
@pseudo-rnd-thoughts @RedTachyon Sure, we could add this, there are actually a ton of environments that can benefit from graph spaces, and I'm actually using them in an upcoming version of [a drone sim for RL](https://github.com/jjshoots/PyFlyt) as well.

That said, a problem with having tutorials for this is that graph spaces are not currently supported in any of the big RL libraries, so it'd probably have to be something done from scratch. Many of the popular tools for Gym will also likely not work with graph spaces mainly because it's a non-homogenous space; the sizes change in every step and you'd need GNNs or Transformers to meaningfully work with them. However, if the goal is to just have a demonstration environment, that can be done pretty easily.

**Comment by Iamfxz** [comment]
I'm using graph space, but I can't use env to represent it. Because the shape is none. So I can only try to convert it to an adjacency matrix, or embed it into a fixed size space.

**Comment by jjshoots** [comment]
@Iamfxz the Graph space is represented by two components, a node space and an edges space. In general, the edges space can take a Box/Discrete space or None, this is something you'll have to define yourself.

We don't generate automatically an adjacency matrix for several reasons, the most obvious of which are that edges can be directed or non-directed, and that the memory footprint of not starting with an adjacency matrix is quite dramatic.

**Comment by Iamfxz** [comment]
@jjshoots I have tried definition. According to my understanding, node_space and edge_space refers to the attributes of node and edge. And then I'm going to convert the graph(NetworkX instance) that I've calculated into GraphInstance. Finally, when I planned to train the model, I found that this was a space for dynamic change. Maybe I need to define all nodes and all possible edges in order to pass into network. So I think it's useful to have an environment that uses Graph definition.
`
class JobShopEnv(gym.Env):
    def __init__(self, env_config=None):
        self.node_space = Box(low=0, high=1, shape=(5,))   # nodes with scaled attributes
        self.edge_space = Discrete(1)   # edge has not attributes
        self.observation_space = Graph(node_space=self.node_space, edge_space=self.edge_space) 
`

**Comment by jjshoots** [comment]
Ah, yes, the node and edge spaces accept dynamic sizes for the number of nodes and edges. The reason is that a graph with fixed number of nodes and a fixed sizes adjacency matrix can just be represented as a Box/Discrete, and then the only trick there is how forward pass is performed.

**Comment by jkterry1** [comment]
In general, I've been highly opposed to adding environments to Gym for things like this in the past. Couldn't this be just created by someone and then linked as a third party environment?

**Comment by RedTachyon** [comment]
I agree with the sentiment, but I'm concerned about adding too many spaces which aren't actually used anywhere else in the library.

**Comment by jjshoots** [comment]
@RedTachyon graph spaces are actually pretty useful imo and it's only a matter of time before the community gets warmer to them imho. My lab is already using them for early experiments.

**Comment by jwwang0-0** [comment]
Is there any update on this issue? I am currently trying to find an example project using graph. It would be super helpful for my project. Thank you!

**Comment by dantp-ai** [comment]
@jkterry1 I was wondering what the state of this issue is. I couldn't find the `JobShopEnv` in the codebase (Btw, there is a subtask in another issue https://github.com/Farama-Foundation/Gymnasium/issues/28 looking for an example or tutorial using the Graph space).

Maybe @Iamfxz, you can add your `Graph` environment as part of a tutorial?

**Comment by jkterry1** [comment]
Gym has been deprecated in favor of gymnasium years ago

**Comment by dantp-ai** [comment]
Ah, sorry, my bad, I somehow thought this also referred to Gymnasium. Forget my comment above.
