### ISSUE TITLE
[Question] Is `gym.spaces.Dict.seed` supposed to be that slow?

### ISSUE THREAD

**Issue by user670** [openai/gym#2937]
I'm trying out [MineDojo](https://github.com/MineDojo/MineDojo), a library that itself imports `gym`.

When I tried to follow the guide, Python seemingly hangs while taking up 8GB of RAM. I slapped a bunch of `print` statements all over MineDojo and Gym's code, and found out it was this function call being very slow: https://github.com/openai/gym/blob/7f6effbc0de59f2b001ef27937ad06dbd9d125e4/gym/spaces/dict.py#L119

where `np.iinfo(int).max` is 2147483647 for me. Is such a slow execution and high RAM cost intended?

I'm running the code on my laptop, Windows 10 x64 home edition, Python 3.10, gym 0.21.0.

Issue cross-reference: https://github.com/MineDojo/MineDojo/issues/5

**Comment by pseudo-rnd-thoughts** [comment]
Could you provide some basic code to replicate your high ram usage and slow function calls. 
But I'm a bit surprised at your code suggestion. 
Looking at the documentation for ['iinfo'](https://numpy.org/doc/stable/reference/generated/numpy.iinfo.html) then the max value of a python integer should be returned. Therefore the large integer you have link so I don't think it should be related to that but example code will help understand

**Comment by RedTachyon** [comment]
So one disclaimer is that gym 0.21.0 is outdated, and in particular the whole `np_random` thing has been significantly reworked since.

That being said, I can see this still being an issue, this piece of code is... weird and needs some attention.

That being said once again, I can't seem to replicate it at the moment. How large of a sample are you using?

And a final note is that in my experience, Windows can mess with a lot of stuff when it comes to numpy stuff and the likes. I once had it slow down TensorFlow computation for no good reason, to the point of unusability.

**Comment by user670** [comment]
SOLVED: with gym 0.24, it no longer does that.
