### ISSUE TITLE
[Bug Report] Minor Issue with Error Message Directing to HTTPS version of non-HTTPS Roboti.us website 

### ISSUE THREAD

**Issue by alphazwest** [openai/gym#2995]
**Describe the bug**
When running e.g. `pip install gym[all]` or another similar command such that `mujoco-py` is installed, on error the following message is displayed:
```
Exception:
    You appear to be missing MuJoCo.  We expected to find the file here: C:\Users\pc\.mujoco\mjpro150

    This package only provides python bindings, the library must be installed separately.

    Please follow the instructions on the README to install MuJoCo

        https://github.com/openai/mujoco-py#install-mujoco

    Which can be downloaded from the website

        https://www.roboti.us/index.html
```
This suggests visiting the roboti.us website, using HTTPS protocol. However, the website is no longer secured via HTTPS and most modern browsers indicate an error to the user similar to "the website can't provide a secure connection."

Possible fixes include:

1.) change the error message to display the HTTP version of the link. (easier, likely still to trigger a browser _warning_)
2.) Have the roboti.us domain provide HTTPS support. 

**Code example**
This Exception was in response to running the `pip install gym[all]` 

Gym was installed via `pip install gym`. After working on another project that required an additional dependency, per suggestions via the console from gym, the `pip install gym[all]` command was executed.

**System Info**
Running Windows 10 Pro 10.0.19044 / Python 3.8.6

**Comment by RedTachyon** [comment]
I'm not sure if this is an issue on our side? Mujoco envs have a weird status, because there's one set of envs with the old bindings from https://github.com/openai/mujoco-py, and another set with the updated, open-source DeepMind mujoco. 

We don't really have control over either of those. Does the error originate from this repo, or from openai/mujoco-py?

**Comment by andrewzhang505** [comment]
I've also encountered this error. The issue seems to be that this error message appears even if you are using the new DeepMind mujoco as long as `mujoco-py` is installed. Installing only the DeepMind dependencies using `pip install gym[mujoco]` works fine but `pip install gym[mujoco, mujoco-py]` does not. 

This bug seems to only be present in gym version 0.25.0 and not 0.24.1. Since gym does no longer maintains environments that depend on mujoco-py, it could be a quick fix to remove `mujoco-py` from `setup.py` so that it is not installed by `pip install gym[all]`

**Comment by pseudo-rnd-thoughts** [comment]
@RedTachyon The warning is outside of gym (at least I looked in all of the normal places and searching didn't find anything)
@andrewzhang505 The warning is part of `mujoco-py` so only when you install `mujoco-py` will a warning be raised.
