### ISSUE TITLE
I have a custom environment and wanted to visualise where the agent is moving in the 3d image array,how can i do that ? 

### ISSUE THREAD

**Issue by muk465** [openai/gym#3000]

**Comment by RedTachyon** [comment]
Hi, the issues here are meant specifically for things related to gym, primarily about its development and technical issues, sometimes supporting the usage of the library itself.

You're asking about something completely unrelated, which happens to use gym among other things, so this is not really the right place. Probably some graphics/geometry/visualization forum, since it's not even that inherent to RL
