### ISSUE TITLE
[Bug Report] Toy code snippet in Readme just doesn't work

### ISSUE THREAD

**Issue by xy9485** [openai/gym#3051]
**Describe the bug**
Toy code snippet reports error on gym 0.25.2 and also with a typo "truncarted"...

**Code example**
```
import gym
env = gym.make("CartPole-v1")
observation, info = env.reset(seed=42)
for _ in range(1000):
    action = env.action_space.sample()
    observation, reward, terminated, truncarted, info = env.step(action)

    if terminated or truncated:
        observation, info = env.reset()
env.close()
```
**Update**
regarding "info" of the return of env.reset(), the discriptions in the source code and the official doc(https://www.gymlibrary.dev/content/api/#resetting) doesn't match each other.

BTW, similar inconsistency can also be found when comparing the recommended toy code snippet in Readme with the one in official doc (https://www.gymlibrary.dev/content/api/#initializing-environments)

This can be super confusing for a gym-beginner and I couldn't trust the accuracy of the official doc at the moment.
I wish the doc to keep at least the same pace as the source code on the master branch.

**Comment by pseudo-rnd-thoughts** [comment]
Thanks for the PR but the cause of the issue is that we have recently undertaking a number of changes to the API including `reset` with `info` and with the `step`. Therefore, it is expected that the website for v25.2 and master are different.
I believe the documentation on master is accurate for the master version with the website hopefully being accurate to `v25.2`

I agree about the comment for gym-beginners but the API changes will stop soon and hopefully bug fixes will be the only changes
