### ISSUE TITLE
[Bug Report] Something is broken in graph spaces/tests

### ISSUE THREAD

**Issue by RedTachyon** [openai/gym#3068]
This popped up in an unrelated CI run: https://github.com/openai/gym/runs/8204126242?check_suite_focus=true

Half the issue is the fact that the [test](https://github.com/openai/gym/blob/master/tests/spaces/test_graph.py#L48) is stochastic (along with other tests in that file) because it is not seeded. 

The other half is that, well, it fails (sometimes). It seems to have been added in #3047 - @pseudo-rnd-thoughts do you know if the test is incorrect (ignoring randomness), or if there's something messed up in the implementation?

**Comment by RedTachyon** [comment]
From a quick check, this seems to happen roughly 1% of the time, so that's fun

**Comment by pseudo-rnd-thoughts** [comment]
Yes, that is very strange. Investigating

**Comment by pseudo-rnd-thoughts** [comment]
The cause is `num_edges = self.np_random.integers(num_nodes * (num_nodes - 1))` which can be zero. 
If so, then the `sampled_edge_space` is None which then means the `edges=None` resulting in the following issue. 

Im not sure what the correct solution should be, either we fix the test through letting the `sample.edge == edge or np.all(sample.edge == 1)`
Or  we make the number of edges >= 1
