### ISSUE TITLE
[Question] can i make with gym custom env  for pc games ?

### ISSUE THREAD

**Issue by troller08** [openai/gym#3120]
### Question
Hello i know i am a idiot but i want to learn how to make a custom env for a pc game (i want it for street fighter x tekken) but i dont know how to make one i tried wekks now but the only tutorials are for py games or with out any context or generic and i am rly sorry for asking i have medium knowledge with python and other programing languages but i just cant understand how to do it my self if i dont see a  simple example  like for a simple pc game with .exe not .py with simple lines of code i only want to learn how to make a ai to play  this game   i dont want to make something extraordinary mmo like thing i just need the ai to press buttons and get rewards from the damage or health reduction etc i have the pointers and i can make a ai with neat but i need the damn custom env 
thnx sorry for my bad English or my pointless rant but i try to understand this for weeks now with 6 hours of sleep and i being desparate trying to understand how to make one 
so thnx for the kind soul that will help me to surpass this damn problem of mine  
<B

**Comment by balisujohn** [comment]
I would think in terms of input and output. So the central challenges are, can you get screenshots of the game from a python program, and can you send key-presses to the game from a python program? If you can handle this in the step and reset functions of the gym environment, you can provide an abstraction which can be used in at least non-vectorized RL. I want to emphasize that your interface doesn't have to be nice.

I don't know what kind of referesh rate you'll get with this, but this is a good place to look for starting to think about collecting observations: https://stackoverflow.com/questions/40809729/can-python-get-the-screen-shot-of-a-specific-window

This might be worth looking at for solving the action side of the interface, thought I didn't read through it carefully so I can't 100% confirm it will work: https://www.reddit.com/r/learnpython/comments/22tke1/use_python_to_send_keystrokes_to_games_in_windows/.

Note that these interfaces should in theory care little about the details of the game they are interacting with, so long as the game uses the operating system's window manages and accepts keypresses. 

Getting reward is trickier, since your observations are screenshots to start, you will need to use some premade computer vision if you want a reward derived from observations which is independent of your policy. opencv is a good place to start, but maybe you will want some sort of dedicated python package for optical character recogintion.

**Comment by troller08** [comment]
> I would think in terms of input and output. So the central challenges are, can you get screenshots of the game from a python program, and can you send key-presses to the game from a python program? If you can handle this in the step and reset functions of the gym environment, you can provide an abstraction which can be used in at least non-vectorized RL. I want to emphasize that your interface doesn't have to be nice.
> 
> I don't know what kind of refresh rate you'll get with this, but this is a good place to look for starting to think about collecting observations: https://stackoverflow.com/questions/40809729/can-python-get-the-screen-shot-of-a-specific-window
> 
> This might be worth looking at for solving the action side of the interface, though I didn't read through it carefully so I can't 100% confirm it will work: https://www.reddit.com/r/learnpython/comments/22tke1/use_python_to_send_keystrokes_to_games_in_windows/.
> 
> Note that these interfaces should in theory care little about the details of the game they are interacting with, so long as the game uses the operating system's window manager and accepts keypresses.
> 
> Getting reward is trickier, since your observations are screenshots to start, you will need to use some premade computer vision if you want a reward derived from observations which is independent of your policy. opencv is a good place to start, but maybe you will want some sort of dedicated python package for optical character recognition.

thx bro i have the pointers for the rewards from game's ram using cheat engine i just need to make a custom env to do as the gym retro  env=gym.make("SFTK") for the ai to press buttons in the game but i need to have a custom env for this otherwise i can not use this self.env.step(actions) actions are the buttons

**Comment by balisujohn** [comment]
Basically you'll need to create a subclass of gym.env and then implement the __init__ step and reset functions yourself. There are tutorials online for how to do it, but they might be out of date with the current gym API so be aware of that.

**Comment by troller08** [comment]
ok bro thnx you for helping me i appreciate that i wish you the best
