### ISSUE TITLE
[Question] Half cheetah xml_file documentation

### ISSUE THREAD

**Issue by esquires** [openai/gym#3134]
### Question

On the gym documentation [website](https://www.gymlibrary.dev/environments/mujoco/half_cheetah/) it says one can override the xml file as follows:

> v3 and v4 take gym.make kwargs such as xml_file, ctrl_cost_weight, reset_noise_scale etc.

```python
env = gym.make('HalfCheetah-v4', ctrl_cost_weight=0.1, ....)
```

Looking at the source code though it appears that half_cheetah_v4.py hard codes the xml file. Is there interest in updating the code to be able to override the xml file? Here is a fix.

```
diff --git a/gym/envs/mujoco/half_cheetah_v4.py b/gym/envs/mujoco/half_cheetah_v4.py
index b30c2861..4d66c54e 100644
--- a/gym/envs/mujoco/half_cheetah_v4.py
+++ b/gym/envs/mujoco/half_cheetah_v4.py
@@ -143,6 +143,7 @@ class HalfCheetahEnv(MujocoEnv, utils.EzPickle):

     def __init__(
         self,
+        xml_file="half_cheetah.xml",
         forward_reward_weight=1.0,
         ctrl_cost_weight=0.1,
         reset_noise_scale=0.1,
@@ -178,7 +179,7 @@ class HalfCheetahEnv(MujocoEnv, utils.EzPickle):
             )

         MujocoEnv.__init__(
-            self, "half_cheetah.xml", 5, observation_space=observation_space, **kwargs
+            self, xml_file, 5, observation_space=observation_space, **kwargs
         )

     def control_cost(self, action):

```

**Comment by pseudo-rnd-thoughts** [comment]
Interesting question, I think this was removed a couple of versions ago because this documentation was forgotten. 
I think we would be interested to re-add this feature for all of the mujoco envs. 
However, we currently not accepting new features on gym but rather on [gymnasium](https://github.com/Farama-Foundation/Gymnasium) if you were interested in re-adding this feature.

**Comment by esquires** [comment]
Thanks!
