### ISSUE TITLE
Continue recording after episode end

### ISSUE THREAD

**Issue by Loviken** [openai/gym#346]
Hi, I am using the mujoco humanoid environment and I would like to continue recording what the agent is doing, even after an episode has ended. However when I try to, I continue to get the following message:

"Trying to step environment which is currently done. While the monitor is active, you cannot step beyond the end of an episode. Call 'env.reset()' to start the next episode."

Is there a way to get around this?

Thanks!

**Comment by Nestor94Gonzalez** [comment]
Not sure if this will help you, but you could try `env.monitor.flush(force=True)`.

**Comment by christopherhesse** [comment]
It looks like you have a wrapper which is checking this, such as this one: https://github.com/openai/gym/blob/5404b39d06f72012f562ec41f60734bd4b5ceb4b/gym/wrappers/monitoring/stats_recorder.py#L45

Try using the environment without that wrapper (creating it directly if you have to from the python class), in order to avoid this issue.
