### ISSUE TITLE
is resetting to a random frame possible?

### ISSUE THREAD

**Issue by hs105** [openai/gym#371]
env.reset() only support the starting frame of games. 

can you make it to resetting to a random frame? Collecting samples will be more efficient if you make it that way.

**Comment by tlbtlbtlb** [comment]
I'm not sure what you mean. Is there an example of a real video game that supports what you have in mind?

**Comment by nwayt001** [comment]
I believe what hs105 is asking is if there is a way to drop an agent in some random state of the environment. Take Atari's montezuma's revenge for example: instead of at starting the agent at the same position in the first room every time an episode ends (which is what env.reset() will do), it would be nice to be able to start the agent in a random place/room at each episode to help with agent exploration. 

I'll try to answer the question with respect to the atari environment because that's the only one I'm familiar with. As far as I know, it's not possible to set, reset or initialize the agent in a random position/state in the atari environment since that's not how the original ROM games work.  You can't expect the emulator to provide you a random state to start in. However, you can specify the state you want the agent to start in by using ale.restoreState() function which takes in a game 'state' as input.  This requires you to have a state on hand to provide the emulator with.  So, you could randomly run an agent and save a bunch of states in a database, then later you can randomly pull from this database to start your agent from pseudorandom positions. 

This issue talks more about saving and restoring environment states [https://github.com/openai/gym/issues/402](https://github.com/openai/gym/issues/402)

**Comment by christopherhesse** [comment]
As @nwayt001 mentioned, some environments support restoring state.  This should already be possible for atari games but does not in general work on gym environments.
