### ISSUE TITLE
Support for querying legal actions

### ISSUE THREAD

**Issue by michalgregor** [openai/gym#413]
Hello, this is to open a discussion concerning the possibility of adding support for querying which actions are legal in a given state. In some environments, such as board games, where action legality is easily determined, this would be a useful concept to have.

The concept of action legality is already present in some environments in an unofficial way – such as board's get_legal_coords() in envs/board_game/go.py. I am thus merely suggesting making such information accessible in a more general way, where it is already available.

Note that it would be very easy to provide a default fallback implementation for the existing environments (and for environments where the concept of action legality does not naturally arise, or is difficult to implement). It would be quite sufficient to return the entire action space in those cases.

As a side-note: Although the concept of action legality is probably most commonly encountered in discrete action spaces, in general, it makes just as much sense in the case of continuous actions. In either case the space of legal actions is a subspace of the original action space. Ideally, we should be able to express piecewise continuous action spaces as well, but I would admit that that might be something of an overkill.

On the practical side: I would be more than happy to help in implementing this. I would, however, first like to get some feedback on what would be considered a good interface. Should we implement this as a primary environment function (in addition to interfaces such as _step and _reset), or would it be better to adopt the approach from go.py and insert an object with a standardized interface and under a standardized key into the dictionary, which _step already returns?

**Comment by bstriner** [comment]
This sounds like a useful feature but can get complicated for Box spaces. Easy to implement for Discrete spaces but need buy-in if you want it to be standardized.

Need to be able to assess available actions before the first step is taken, so it could be a separate API, or additional info returned by both step() and reset().

For Discrete spaces, there could be a list of actions or a function that checks if an action is valid. For continuous spaces, you can't return a list of actions and a function that checks if an action is valid is of limited use. Assuming the valid space is a union of box spaces, maybe you could put something together.

Just talking about Discrete spaces, I would suggest something like adding a key "available_actions" to the info. If the info has that key, then the environment supports available actions.

Cheers,
Ben

**Comment by michalgregor** [comment]
It is a good point that we need available actions before we take the first step. That seems to argue in favour of delegating this functionality to a separate method altogether – because adding another return value to reset() would break existing code – which only expects it to return the state observation.

If we had an additional method, e.g. getLegalActions() or something on those lines and the protocol would be to only call this once reset() has been called (to ensure that the environment has been properly initialized first), can you think of any major downsides?

**Comment by tlbtlbtlb** [comment]
No plans to expose this in the API. A sufficiently smart agent should be able to figure out the legal actions.

**Comment by joellutz** [comment]
In my own environment (which controls a real machine) I also had to use the information about the legal actions in each timestep. I put them as a list in the info dict, which is returned in the standard API of the step() function. But I had to modify the reset() function, so that it also returns the info dict, which worked fine for me.

Even though it's true what @tlbtlbtlb says, when interacting with a real world environment is the only option (because it can't be simulated properly), it may not be possible to train an agent for many thousands transitions so that it learns which actions are legal in a state. In this case it is necessary to have the information about the currently legal actions also in the beginning of an episode (i.e. after the reset() function call). But as long as I can modify the reset() function for my environment and agent, I don't see a urgent necessity for this to be included in the standard API.

**Comment by turmeric-blend** [comment]
hi @joellutz , you said u passed a list of legal actions through the info dict at reset() and step() functions, but did u passed them as an observation/state into the neural network of the learning model? Otherwise, how does your learning agent gets informed about what actions are legal and what are not, and how does it deal with it?

**Comment by joellutz** [comment]
Hi @turmeric-blend . Yes, I did in fact pass the legal actions for each observation into my q-value estimator, along with the corresponding state of course. In order for my estimator to "learn" which actions are legal an which are not, I used a hack: In the q-value prediction for a given state and its legal actions in that state, I predicted all q-values for all actions with my function approximation and then simply assigned each illegal action a low q-value afterwards. (My action space was discrete.)
This was good enough for my case, but a better way of course would be if the function approximation (e.g. neural net) itself learned which actions are allowed for a given state. You could do that for example by training the function approximation with pairs of state and illegal actions for that state and assigning a low reward for these state-action-pairs. For the actual (executed) state-action-pair, you use the received reward of course.
