### ISSUE TITLE
Make tips more prominent; also make score easy to access

### ISSUE THREAD

**Issue by gdb** [openai/gym#45]
From chat:

```
@gdb I vote for adding helpful tips like video_callable=lambda count: False somewhere prominent. I found it very here https://github.com/openai/gym/blob/master/gym/monitoring/monitor.py#L73 (after knowing to look for it from having read about it earlier in chat here).
Is there a way that I can easily print the performance of my agent using the monitor without? I've briefly tried inspecting the tmp file. That would be a nice thing to add somewhere to the intro docs too. I imagine folks will want to iterate quickly on their code and do this all the time.
episode_rewards in the tmp file looks the right thing. I guess I could track this myself. Nice to give folks a way to print this out out-of-the-box, though.
```

**Comment by JKCooper2** [comment]
PR for easier local score access (should also help stop submits being flooded to the server when people are only trying to test):
https://github.com/openai/gym/pull/57

**Comment by JKCooper2** [comment]
Should this and issue #7 be closed now the PR is done?

**Comment by gdb** [comment]
There's still the first part, of making common usage patterns more available. I think either adding to the README, or having a richer set of examples — what do you think?

**Comment by JKCooper2** [comment]
I think the spread of functionality knowledge will mostly be a natural result of people viewing other peoples implementations. If I see someone else's code that uses video_callable=lambda x: False then I'm more likely to use it myself and look into how it works. 

For that it would be beneficial to have something like a readthedocs site (e.g. https://rllab.readthedocs.io/en/latest/) so that the community can update information through pull requests, as well as a place for listing changes in releases and what's involved. If there's a new feature I would like to be able to see that there's a new feature without having to trawl through documentation looking for changes (like this PR). This could just be a single page on readthedocs with links to the corresponding explanatory pages.

However I think it's very important to distinguish between docs that explain how the OpenAI gym works and information that explain how RL in general works. https://gym.openai.com/docs/rl has lots of useful information on it (and I really like the idea of exercises), but having under docs will eventually become confusing. Something like a library or knowledge base (or whatever you want to call it) that can contain information about RL (concept) that has links to and from the code docs (implementation) could work. 

I think there'll end up being a third hybrid part which will be ipython notebooks that explain the theory along with implementations of specific algorithms you can play around with but that they should be separate again

**Comment by gdb** [comment]
Kk. Closing this for now. I think it'll probably be helpful for us to add a forum soon, and see what wisdom emerges there.
