### ISSUE TITLE
AttributeError: 'TimeLimit' object has no attribute 'x_threshold' 

### ISSUE THREAD

**Issue by MorvanZhou** [openai/gym#537]
Thanks for your great work.

I had gym 0.7.3 installed before and I can use the env attributes like "x_threashold" in Cartpole.
But now, in gym 0.7.4 and higher, I cannot use those anymore. 

Also, in MountainCar, LunnarLander and possibly more, the episode seems to be limited to some time range. Hope that be fixed soon.

**Comment by tlbtlbtlb** [comment]
If you're trying to munge attributes of the environment (which renders your learning results not comparable with anyone else's) you can get at the raw environment with `env.unwrapped`, as in  `env.unwrapped.x_threshold = -1`

The episode is indeed limited to a time range, by design. An environment with unlimited time isn't as challenging to solve.

**Comment by MorvanZhou** [comment]
Thanks
