### ISSUE TITLE
What is the observation space of an env?

### ISSUE THREAD

**Issue by pootlins** [openai/gym#593]
Hi,

I have a custom gym environment and i have found that I need to set its observation_space. I have read through the gym docs, looked at its use in cartpole, looked at the spaces folder, but I do not understand what it conceptually is and how/with what I should set it. How can I find this out?

Thank you

**Comment by tlbtlbtlb** [comment]
The `observation_space` defines the structure of the observations your environment will be returning. Learning agents usually need to know this before they start running, in order to set up the policy function. Some general-purpose learning agents can handle a wide range of observation types: Discrete, Box, or pixels (which is usually a `Box(0, 255, [height, width, 3]`) for RGB pixels).

See at https://gym.openai.com/docs under **Spaces**.

**Comment by cserpell** [comment]
Shouldn't this issue be closed?

**Comment by yangpeiren** [comment]
@toenailssauce Represents the RGB value respectively.

**Comment by AloshkaD** [comment]
How to go about defining observation_space where two images are passed as a state?

**Comment by yangpeiren** [comment]
use Dict or Tuple, the code is [here](https://github.com/openai/gym/blob/master/gym/spaces/dict_space.py).

**Comment by AloshkaD** [comment]
Thank you @yangpeiren I saw that. the problem is baseline supports boxes obs_spaces only which is a bummer :(

**Comment by yangpeiren** [comment]
@AloshkaD , you are welcome, actually the [Ray Rllib](https://ray.readthedocs.io/en/latest/rllib.html) from UC Berkeley supports Dict and Tuple, however the learning curve of it is steep, since it is a quite large framework.

**Comment by biplavc** [comment]
Are state and observation space the same thing?
