### ISSUE TITLE
Continuous control with raw pixels?

### ISSUE THREAD

**Issue by mpgussert** [openai/gym#598]
Greetings all!  

Can anyone point me to an environment that uses raw pixels for an observation but has a continuous action space?  

If not, is there a way to get the pixels in, for example, pendulum-v0 without actually displaying the window?

thanks!

**Comment by praveen-palanisamy** [comment]
[`CarRacing-v0`](https://gym.openai.com/envs/CarRacing-v0/)  is an environment that uses raw pixels for observations and has a continuous action space. The observations are images with 96x96 pixels of a top-down racing environment. The action space is `Box(3,)` for steer, gas/throttle and brake. You can also use other environments like `RoboschoolHopper-v1`.

For your second question: You can get the pixels as an `rgb_array` by using the `rgb_array` render mode instead of `human` which is the default. You can for example get the array of pixel values using: `im_frame = env.render(mode='rgb_array')`

**Comment by FlavioLorenzi** [comment]
@praveen-palanisamy Hi, I have a big problem in Car-Racing when I try to use the Renforcement Learning algo (SAC) in https://github.com/openai/spinningup/tree/master/spinup/algos .
I think that is a correlated problem to the pixel of the image with shape =(96,96,3),
because I have the following error: **ValueError: could not broadcast input array from shape (96,96,3) into shape (96).**
I would know if there is a way to reduce (resize) the shape of observation space, because in SAC it expected a value of size one.

**Comment by praveen-palanisamy** [comment]
@FlavioLorenzi The SAC implementation in OpenAI' Spinning up repository works only for a single dimensional state vector. With the CarRacing environment, it is expecting a shape of `96` as a direct consequence of this line of code:

https://github.com/openai/spinningup/blob/8b92b8a6fb1de63de59be61cd7a9a6ab7304c283/spinup/algos/sac/sac.py#L139

You could apply an observation wrapper to the CarRacing gym environment  to convert the (96, 96, 3) image input to a single dimensional vector (one naive way is to just flatten the (96, 96, 3) matrix into a (96 * 96 *3) vector).

There are other options but it depends on what you are looking for. If you definitely want to use SAC, then you could use [this implementation](https://github.com/haarnoja/sac) or modify the spinning-up repo's SAC implementation to work with image inputs.

**Comment by christopherhesse** [comment]
Thanks for answering this @praveen-palanisamy!  Spinning up does not support pixel observations, as discussed here: https://github.com/openai/gym/issues/1267
