### ISSUE TITLE
How to obtain the max/min step reward for a specific Atari environment? or set the reward range to (-1.0,+1.0)?

### ISSUE THREAD

**Issue by YuhangSong** [openai/gym#601]
I am working on a project that need to normalized step reward of different games to a controlled range, (-1.0, 1.0). So, it is required for me to obtain the step reward range or set it (it would be better if I can set it without any side-effect on the game emulator).

You are doing a great job, appreciate for your contribution of the Open AI Gym!! Believe many are benefit from it a lot.

**Comment by babak-badnava** [comment]
I need this feature too. I will be thankful if you give me a hint how to do normalize rewards between [-1,1]

**Comment by christopherhesse** [comment]
I'm afraid those are not available.  You can however use the scores available in a few published papers such as https://arxiv.org/pdf/1706.10295.pdf and normalize based on those, so that the sum of rewards will be usually < 1.

There's also something like https://github.com/openai/baselines/blob/master/baselines/common/vec_env/vec_normalize.py that can do this for arbitrary environments.

**Comment by zdrnjabk4** [comment]
Wait, I might be late to join the party, and might be missing the point, but why don't you just clip the reward after it's returned from the environment? Like use `np.sign(reward)` or an equivalent?
