### ISSUE TITLE
Error in resetting the environment on overriding reset function of Env class  

### ISSUE THREAD

**Issue by shristi945** [openai/gym#695]
I am writing my own environment for autonomous drone hence defining _step() and _reset() fun in myenv class.
this is the code for my environment 

![env_code](https://user-images.githubusercontent.com/28530708/29447632-699149a2-8410-11e7-8e9a-54f0fdf730ea.JPG)
and these are the errors 

![env_error](https://user-images.githubusercontent.com/28530708/29447649-7d729d86-8410-11e7-8851-20d724891374.JPG)

Please can anyone help me with these errors. Thanks in Advance.

**Comment by olegklimov** [comment]
I'm afraid your errors are very basic. Nothing to do with gym.

**Comment by benelot** [comment]
Your particular problem at hand is that your step method takes the action
argument and you do not provide one. Regarding the bigger picture, I would
recommend you to take one of the existing gyms and remodel it to do the
thing you want to do with the drones. That way you start with a running
example and you can rewrite its parts while always keeping it in a running
state (never make the code break at any point is the motto here). It is far
easier to debug what you do if you develop it in that manner because you
can always run it and test if it works so far.

**Comment by shristi945** [comment]
@benelot  Hi thanx for your response can you tell me what is to provide as an action argument to run the step function. I am confused what exactly is to be passed in argument action is not defined anywhere in the code of environment even not in the existing environments that are already there on gym.
Thanx

**Comment by benelot** [comment]
The action is what is handed in by the agent (your learning algorithm) to
control the environment. So producing the action is not part of the
environment but of the agent performing in it. You can look at this for
instance in the keyboard agent, where you yourself are the learning agent
by controlling the environment using your keyboard:
https://github.com/openai/gym/blob/master/examples/agents/keyboard_agent.py
