### ISSUE TITLE
Documentation improvement

### ISSUE THREAD

**Issue by keleftheriou** [openai/gym#70]
core.py states:
```reward (float) : amount of reward due to the previous action```
but as I understand it, the reward may not necessarily be due to the *previous* action only.

**Comment by tlbtlbtlb** [comment]
The reward should be a function of only the previous state and action. To get good rewards, you have to plan ahead to get into states where there are good actions to take.

**Comment by alexnikulkov** [comment]
Can we come back to this question? I think the reward is actually a function of the current state and action, not previous. A few examples from the simpler environments where it's really obvious:
-[Pendulum](https://github.com/openai/gym/blob/master/gym/envs/classic_control/pendulum.py#L114)
- [CMC](https://github.com/openai/gym/blob/master/gym/envs/classic_control/continuous_mountain_car.py#L147-L153)

Also, I'd argue that returning the reward due to previous action is problematic conceptually because for the first step() call there is no last action; and the last action's reward would end up being discarded since there's no next step
