### ISSUE TITLE
Mujoco License

### ISSUE THREAD

**Issue by laksefest** [openai/gym#717]
Why cant OpenAI/GYM use something free? There are no other free physics engine that can be used? Im not a student and I dont have 500$ to pay for Mujoco every year. This is such a disappointment.

**Comment by lukashermann** [comment]
For some environments, there is a free alternative: 
https://blog.openai.com/roboschool/

**Comment by erwincoumans** [comment]
You can also use pybullet Gym environments, it has environments like Ant, Humanoid, Hopper etc, but also new ones like Minitaur, Racecar and KukaGrasp. Unlike Roboschool and MuJoCo, pybullet installation is very simple: pip install pybullet
and the user manual is here:[ http://pybullet.org]( http://pybullet.org)

**Comment by jtoy** [comment]
as @erwincoumans mentioned,  If you have the flexibility, you could use bullet/pybullet. I had the same issue and moved my experiments to pybullet without hassle. Moving had the benefit of making environment setup/deployment much easier for me as well.

**Comment by mariusa** [comment]
OpenAI staff, would you please make pybullet implementation the default one? It would ease adoption by new users.

Please see https://github.com/benelot/pybullet-gym

**Comment by josiahls** [comment]
Like seriously, if you have a project with the word "open" and then use a proprietary backend, what's the point in calling yourself open? I have spent the past few trying to get the environment installed on a job based server, but in the end, if you have a license tied to an id, and the job lands on a different node, then you're screwed anyways.

**Comment by gandalf1819** [comment]
How many days does it take for the license to get approved if you apply as a student?

**Comment by kargarisaac** [comment]
@gandalf1819 
It seems it will take forever. they don't answer emails

**Comment by christopherhesse** [comment]
Roboschool and Pybullet are now mentioned on the environments page: https://github.com/openai/gym/blob/master/docs/environments.md

@erwincoumans let me know if there's a better link for the description for Pybullet, the google docs user manual was the only reference I could find for what environments were available.

I think we're unlikely to just replace the mujoco environments because they serve as reference points for papers, but either Roboschool or Pybullet offer license-free 3d physics environments, so people should generally prefer those if they don't need mujoco.

**Comment by christopherhesse** [comment]
Closing this issue as I think roboschool and pybullet serve this purpose well.
