### ISSUE TITLE
Almost finished @j8lp 's tutorial, error at end...tried other things out of them one thing worked but error again

### ISSUE THREAD

**Issue by deep999** [openai/gym#749]
I'm stuck at second part of  @j8lp tutorials 5th step:"cd atari-py && make && python setup.py install && pip install "gym[atari]"", if I run it in cmd:
D:\Anaconda\envs\tensorflow>cd atari-py && make && python setup.py install &&
 pip install "gym[atari]"
'make' is not recognized as an internal or external command,
operable program or batch file."

I also tried pip install gym, then get error in pycharm that atari-py is missing, I install it with "D:\Anaconda\envs\tensorflow>pip install gym[atari]", then this error occurs:
Traceback (most recent call last):
  File "C:/Users/PycharmProjects/MachineLearning/sentdex_TF/2.py", line 5, in <module>
    env = gym.make('Pong-v0')
  File "D:\Anaconda\lib\site-packages\gym\envs\registration.py", line 164, in make
    return registry.make(id)
  File "D:\Anaconda\lib\site-packages\gym\envs\registration.py", line 122, in make
    env = spec.make()
  File "D:\Anaconda\lib\site-packages\gym\envs\registration.py", line 88, in make
    cls = load(self._entry_point)
  File "D:\Anaconda\lib\site-packages\gym\envs\registration.py", line 17, in load
    result = entry_point.load(False)
  File "D:\Anaconda\lib\site-packages\setuptools-27.2.0-py3.6.egg\pkg_resources\__init__.py", line 2258, in load
  File "D:\Anaconda\lib\site-packages\setuptools-27.2.0-py3.6.egg\pkg_resources\__init__.py", line 2264, in resolve
  File "D:\Anaconda\lib\site-packages\gym\envs\atari\__init__.py", line 1, in <module>
    from gym.envs.atari.atari_env import AtariEnv
  File "D:\Anaconda\lib\site-packages\gym\envs\atari\atari_env.py", line 9, in <module>
    import atari_py
  File "c:\users\atari-py\atari_py\__init__.py", line 1, in <module>
    from .ale_python_interface import *
  File "c:\users\atari-py\atari_py\ale_python_interface.py", line 14, in <module>
    'ale_interface/build/libale_c.dll'))
  File "D:\Anaconda\lib\ctypes\__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "D:\Anaconda\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] Given module can't be found

If I try(as in https://github.com/openai/gym/issues/672) error is:
    error: command 'D:\\Anaconda\\Library\\mingw-w64\\bin\\gcc.exe' failed wi
th exit status 1

    ----------------------------------------
  Rolling back uninstall of atari-py
Command "d:\Anaconda\python.exe -u -c "import setuptools, tokenize;__file__='
C:\\Users\\AppData\\Local\\Temp\\pip-2dbb83b_-build\\setup.py';f=getattr(
tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();
exec(compile(code, __file__, 'exec'))" install --record C:\Users\URO~1\AppData\L
ocal\Temp\pip-wd7z84h6-record\install-record.txt --single-version-externally-man
aged --compile" failed with error code 1 in C:\Users\AppData\Local\Temp\pi
p-2dbb83b_-build\

**Comment by j8lp** [comment]
Sorry for the super late reply.  Your problem sounds like Windows can't find the make.exe file.  It's supposed to be in your "C:\msys64\mingw64\bin" folder.  Can you open that folder and tell me what's there?

**Comment by Red-Pheonix** [comment]
I'm having a similiar issue, it turns out that msys doesn't inherit windows path by default, you have to go to where msys2.exe is located and and edit "msys2.ini" file and uncomment the "MSYS2_PATH_TYPE=inherit" line. However, now it finds make but it cant seem to compile. Here's the output-

""make -C atari_py/ale_interface build
make[1]: Entering directory '/D/Programming/Py_script/openai_gym/atari-py/atari_py/ale_interface'
mkdir -p build && cd build && cmake -G "MSYS Makefiles" .. && make -j4
CMake Warning (dev) at CMakeLists.txt:210 (FILE):
  Policy CMP0053 is not set: Simplify variable reference and escape sequence
  evaluation.  Run "cmake --help-policy CMP0053" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  For input:

    '
    IF(NOT EXISTS \"@CMAKE_CURRENT_BINARY_DIR@/install_manifest.txt\")
      MESSAGE(FATAL_ERROR \"Cannot find install manifest: @CMAKE_CURRENT_BINARY_DIR@/install_manifest.txt\")
    ENDIF(NOT EXISTS \"@CMAKE_CURRENT_BINARY_DIR@/install_manifest.txt\")

    FILE(READ \"@CMAKE_CURRENT_BINARY_DIR@/install_manifest.txt\" files)
    STRING(REGEX REPLACE \"\\n\" \";\" files \"\${files}\")
    FOREACH(file \${files})
      MESSAGE(STATUS \"Uninstalling \"\$ENV{DESTDIR}\${file}\"\")
      IF(EXISTS \"\$ENV{DESTDIR}\${file}\")
        EXEC_PROGRAM(
          \"@CMAKE_COMMAND@\" ARGS \"-E remove \"\$ENV{DESTDIR}\${file}\"\"
          OUTPUT_VARIABLE rm_out
          RETURN_VALUE rm_retval
          )
        IF(NOT \"\${rm_retval}\" STREQUAL 0)
          MESSAGE(FATAL_ERROR \"Problem when removing \"\$ENV{DESTDIR}\${file}\"\")
        ENDIF(NOT \"\${rm_retval}\" STREQUAL 0)
      ELSE(EXISTS \"\$ENV{DESTDIR}\${file}\")
        MESSAGE(STATUS \"File \"\$ENV{DESTDIR}\${file}\" does not exist.\")
      ENDIF(EXISTS \"\$ENV{DESTDIR}\${file}\")
    ENDFOREACH(file)
    '

  the old evaluation rules produce:

    '
    IF(NOT EXISTS "D:/Programming/Py_script/openai_gym/atari-py/atari_py/ale_interface/build/install_manifest.txt")
      MESSAGE(FATAL_ERROR "Cannot find install manifest: D:/Programming/Py_script/openai_gym/atari-py/atari_py/ale_interface/build/install_manifest.txt")
    ENDIF(NOT EXISTS "D:/Programming/Py_script/openai_gym/atari-py/atari_py/ale_interface/build/install_manifest.txt")

    FILE(READ "D:/Programming/Py_script/openai_gym/atari-py/atari_py/ale_interface/build/install_manifest.txt" files)
    STRING(REGEX REPLACE "\n" ";" files "${files}")
    FOREACH(file ${files})
      MESSAGE(STATUS "Uninstalling "$ENV{DESTDIR}${file}"")
      IF(EXISTS "$ENV{DESTDIR}${file}")
        EXEC_PROGRAM(
          "C:/Program Files (x86)/CMake/bin/cmake.exe" ARGS "-E remove "$ENV{DESTDIR}${file}""
          OUTPUT_VARIABLE rm_out
          RETURN_VALUE rm_retval
          )
        IF(NOT "${rm_retval}" STREQUAL 0)
          MESSAGE(FATAL_ERROR "Problem when removing "$ENV{DESTDIR}${file}"")
        ENDIF(NOT "${rm_retval}" STREQUAL 0)
      ELSE(EXISTS "$ENV{DESTDIR}${file}")
        MESSAGE(STATUS "File "$ENV{DESTDIR}${file}" does not exist.")
      ENDIF(EXISTS "$ENV{DESTDIR}${file}")
    ENDFOREACH(file)
    '

  but the new evaluation rules produce:

    '
    IF(NOT EXISTS "@CMAKE_CURRENT_BINARY_DIR@/install_manifest.txt")
      MESSAGE(FATAL_ERROR "Cannot find install manifest: @CMAKE_CURRENT_BINARY_DIR@/install_manifest.txt")
    ENDIF(NOT EXISTS "@CMAKE_CURRENT_BINARY_DIR@/install_manifest.txt")

    FILE(READ "@CMAKE_CURRENT_BINARY_DIR@/install_manifest.txt" files)
    STRING(REGEX REPLACE "\n" ";" files "${files}")
    FOREACH(file ${files})
      MESSAGE(STATUS "Uninstalling "$ENV{DESTDIR}${file}"")
      IF(EXISTS "$ENV{DESTDIR}${file}")
        EXEC_PROGRAM(
          "@CMAKE_COMMAND@" ARGS "-E remove "$ENV{DESTDIR}${file}""
          OUTPUT_VARIABLE rm_out
          RETURN_VALUE rm_retval
          )
        IF(NOT "${rm_retval}" STREQUAL 0)
          MESSAGE(FATAL_ERROR "Problem when removing "$ENV{DESTDIR}${file}"")
        ENDIF(NOT "${rm_retval}" STREQUAL 0)
      ELSE(EXISTS "$ENV{DESTDIR}${file}")
        MESSAGE(STATUS "File "$ENV{DESTDIR}${file}" does not exist.")
      ENDIF(EXISTS "$ENV{DESTDIR}${file}")
    ENDFOREACH(file)
    '

  Using the old result for compatibility since the policy is not set.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
-- Generating done
-- Build files have been written to: D:/Programming/Py_script/openai_gym/atari-py/atari_py/ale_interface/build
make[2]: Entering directory '/D/Programming/Py_script/openai_gym/atari-py/atari_py/ale_interface/build'
make[3]: Entering directory '/D/Programming/Py_script/openai_gym/atari-py/atari_py/ale_interface/build'
make[4]: Entering directory '/D/Programming/Py_script/openai_gym/atari-py/atari_py/ale_interface/build'
make[4]: Leaving directory '/D/Programming/Py_script/openai_gym/atari-py/atari_py/ale_interface/build'
make[4]: Entering directory '/D/Programming/Py_script/openai_gym/atari-py/atari_py/ale_interface/build'
[  1%] Building CXX object CMakeFiles/ale-c-lib.dir/src/common/ScreenExporter.cpp.obj
[  2%] Building CXX object CMakeFiles/ale-c-lib.dir/src/common/SoundNull.cxx.obj
[  3%] Building CXX object CMakeFiles/ale-c-lib.dir/src/common/SoundSDL.cxx.obj
[  4%] Building CXX object CMakeFiles/ale-c-lib.dir/src/common/display_screen.cpp.obj
D:/Programming/Py_script/openai_gym/atari-py/atari_py/ale_interface/src/common/ScreenExporter.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
 /* *****************************************************************************
 ^
D:/Programming/Py_script/openai_gym/atari-py/atari_py/ale_interface/src/common/SoundNull.cxx:1:0: warning: -fPIC ignored for target (all code is position independent)
 //============================================================================
 ^
D:/Programming/Py_script/openai_gym/atari-py/atari_py/ale_interface/src/common/SoundSDL.cxx:1:0: warning: -fPIC ignored for target (all code is position independent)
 //============================================================================
 ^
D:/Programming/Py_script/openai_gym/atari-py/atari_py/ale_interface/src/common/display_screen.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
 /* *****************************************************************************
 ^
D:/Programming/Py_script/openai_gym/atari-py/atari_py/ale_interface/src/common/ScreenExporter.cpp:18:18: fatal error: zlib.h: No such file or directory
compilation terminated.
make[4]: *** [CMakeFiles/ale-c-lib.dir/build.make:189: CMakeFiles/ale-c-lib.dir/src/common/ScreenExporter.cpp.obj] Error 1
make[4]: *** Waiting for unfinished jobs....
[  4%] Building CXX object CMakeFiles/ale-c-lib.dir/src/controllers/ale_controller.cpp.obj
D:/Programming/Py_script/openai_gym/atari-py/atari_py/ale_interface/src/controllers/ale_controller.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
 /* *****************************************************************************
 ^
D:/Programming/Py_script/openai_gym/atari-py/atari_py/ale_interface/src/common/SoundNull.cxx: In member function 'virtual bool SoundNull::load(Deserializer&)':
D:/Programming/Py_script/openai_gym/atari-py/atari_py/ale_interface/src/common/SoundNull.cxx:49:9: warning: variable 'reg' set but not used [-Wunused-but-set-variable]
   uInt8 reg;
         ^
make[4]: Leaving directory '/D/Programming/Py_script/openai_gym/atari-py/atari_py/ale_interface/build'
make[3]: *** [CMakeFiles/Makefile2:68: CMakeFiles/ale-c-lib.dir/all] Error 2
make[3]: Leaving directory '/D/Programming/Py_script/openai_gym/atari-py/atari_py/ale_interface/build'
make[2]: *** [Makefile:84: all] Error 2
make[2]: Leaving directory '/D/Programming/Py_script/openai_gym/atari-py/atari_py/ale_interface/build'
make[1]: *** [Makefile:4: build] Error 2
make[1]: Leaving directory '/D/Programming/Py_script/openai_gym/atari-py/atari_py/ale_interface'
make: *** [Makefile:4: build] Error 2

DELL@Rafi MSYS /D/Programming/Py_script/openai_gym/atari-py
$ make
make -C atari_py/ale_interface build
make[1]: Entering directory '/D/Programming/Py_script/openai_gym/atari-py/atari_py/ale_interface'
mkdir -p build && cd build && cmake -G "MSYS Makefiles" .. && make -j4
CMake Warning (dev) at CMakeLists.txt:210 (FILE):
  Policy CMP0053 is not set: Simplify variable reference and escape sequence
  evaluation.  Run "cmake --help-policy CMP0053" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  For input:

    '
    IF(NOT EXISTS \"@CMAKE_CURRENT_BINARY_DIR@/install_manifest.txt\")
      MESSAGE(FATAL_ERROR \"Cannot find install manifest: @CMAKE_CURRENT_BINARY_DIR@/install_manifest.txt\")
    ENDIF(NOT EXISTS \"@CMAKE_CURRENT_BINARY_DIR@/install_manifest.txt\")

    FILE(READ \"@CMAKE_CURRENT_BINARY_DIR@/install_manifest.txt\" files)
    STRING(REGEX REPLACE \"\\n\" \";\" files \"\${files}\")
    FOREACH(file \${files})
      MESSAGE(STATUS \"Uninstalling \"\$ENV{DESTDIR}\${file}\"\")
      IF(EXISTS \"\$ENV{DESTDIR}\${file}\")
        EXEC_PROGRAM(
          \"@CMAKE_COMMAND@\" ARGS \"-E remove \"\$ENV{DESTDIR}\${file}\"\"
          OUTPUT_VARIABLE rm_out
          RETURN_VALUE rm_retval
          )
        IF(NOT \"\${rm_retval}\" STREQUAL 0)
          MESSAGE(FATAL_ERROR \"Problem when removing \"\$ENV{DESTDIR}\${file}\"\")
        ENDIF(NOT \"\${rm_retval}\" STREQUAL 0)
      ELSE(EXISTS \"\$ENV{DESTDIR}\${file}\")
        MESSAGE(STATUS \"File \"\$ENV{DESTDIR}\${file}\" does not exist.\")
      ENDIF(EXISTS \"\$ENV{DESTDIR}\${file}\")
    ENDFOREACH(file)
    '

  the old evaluation rules produce:

    '
    IF(NOT EXISTS "D:/Programming/Py_script/openai_gym/atari-py/atari_py/ale_interface/build/install_manifest.txt")
      MESSAGE(FATAL_ERROR "Cannot find install manifest: D:/Programming/Py_script/openai_gym/atari-py/atari_py/ale_interface/build/install_manifest.txt")
    ENDIF(NOT EXISTS "D:/Programming/Py_script/openai_gym/atari-py/atari_py/ale_interface/build/install_manifest.txt")

    FILE(READ "D:/Programming/Py_script/openai_gym/atari-py/atari_py/ale_interface/build/install_manifest.txt" files)
    STRING(REGEX REPLACE "\n" ";" files "${files}")
    FOREACH(file ${files})
      MESSAGE(STATUS "Uninstalling "$ENV{DESTDIR}${file}"")
      IF(EXISTS "$ENV{DESTDIR}${file}")
        EXEC_PROGRAM(
          "C:/Program Files (x86)/CMake/bin/cmake.exe" ARGS "-E remove "$ENV{DESTDIR}${file}""
          OUTPUT_VARIABLE rm_out
          RETURN_VALUE rm_retval
          )
        IF(NOT "${rm_retval}" STREQUAL 0)
          MESSAGE(FATAL_ERROR "Problem when removing "$ENV{DESTDIR}${file}"")
        ENDIF(NOT "${rm_retval}" STREQUAL 0)
      ELSE(EXISTS "$ENV{DESTDIR}${file}")
        MESSAGE(STATUS "File "$ENV{DESTDIR}${file}" does not exist.")
      ENDIF(EXISTS "$ENV{DESTDIR}${file}")
    ENDFOREACH(file)
    '

  but the new evaluation rules produce:

    '
    IF(NOT EXISTS "@CMAKE_CURRENT_BINARY_DIR@/install_manifest.txt")
      MESSAGE(FATAL_ERROR "Cannot find install manifest: @CMAKE_CURRENT_BINARY_DIR@/install_manifest.txt")
    ENDIF(NOT EXISTS "@CMAKE_CURRENT_BINARY_DIR@/install_manifest.txt")

    FILE(READ "@CMAKE_CURRENT_BINARY_DIR@/install_manifest.txt" files)
    STRING(REGEX REPLACE "\n" ";" files "${files}")
    FOREACH(file ${files})
      MESSAGE(STATUS "Uninstalling "$ENV{DESTDIR}${file}"")
      IF(EXISTS "$ENV{DESTDIR}${file}")
        EXEC_PROGRAM(
          "@CMAKE_COMMAND@" ARGS "-E remove "$ENV{DESTDIR}${file}""
          OUTPUT_VARIABLE rm_out
          RETURN_VALUE rm_retval
          )
        IF(NOT "${rm_retval}" STREQUAL 0)
          MESSAGE(FATAL_ERROR "Problem when removing "$ENV{DESTDIR}${file}"")
        ENDIF(NOT "${rm_retval}" STREQUAL 0)
      ELSE(EXISTS "$ENV{DESTDIR}${file}")
        MESSAGE(STATUS "File "$ENV{DESTDIR}${file}" does not exist.")
      ENDIF(EXISTS "$ENV{DESTDIR}${file}")
    ENDFOREACH(file)
    '

  Using the old result for compatibility since the policy is not set.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
-- Generating done
-- Build files have been written to: D:/Programming/Py_script/openai_gym/atari-py/atari_py/ale_interface/build
make[2]: Entering directory '/D/Programming/Py_script/openai_gym/atari-py/atari_py/ale_interface/build'
make[3]: Entering directory '/D/Programming/Py_script/openai_gym/atari-py/atari_py/ale_interface/build'
make[4]: Entering directory '/D/Programming/Py_script/openai_gym/atari-py/atari_py/ale_interface/build'
make[4]: Leaving directory '/D/Programming/Py_script/openai_gym/atari-py/atari_py/ale_interface/build'
make[4]: Entering directory '/D/Programming/Py_script/openai_gym/atari-py/atari_py/ale_interface/build'
[  1%] Building CXX object CMakeFiles/ale-c-lib.dir/src/common/ScreenExporter.cpp.obj
[  2%] Building CXX object CMakeFiles/ale-c-lib.dir/src/controllers/fifo_controller.cpp.obj
[  3%] Building CXX object CMakeFiles/ale-c-lib.dir/src/controllers/rlglue_controller.cpp.obj
[  3%] Building C object CMakeFiles/ale-c-lib.dir/src/emucore/unzip.c.obj
D:/Programming/Py_script/openai_gym/atari-py/atari_py/ale_interface/src/common/ScreenExporter.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
 /* *****************************************************************************
 ^
D:/Programming/Py_script/openai_gym/atari-py/atari_py/ale_interface/src/controllers/fifo_controller.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
 /* *****************************************************************************
 ^
D:/Programming/Py_script/openai_gym/atari-py/atari_py/ale_interface/src/controllers/rlglue_controller.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
 /* *****************************************************************************
 ^
D:/Programming/Py_script/openai_gym/atari-py/atari_py/ale_interface/src/emucore/unzip.c:11:18: fatal error: zlib.h: No such file or directory
compilation terminated.
make[4]: *** [CMakeFiles/ale-c-lib.dir/build.make:389: CMakeFiles/ale-c-lib.dir/src/emucore/unzip.c.obj] Error 1
make[4]: *** Waiting for unfinished jobs....
D:/Programming/Py_script/openai_gym/atari-py/atari_py/ale_interface/src/common/ScreenExporter.cpp:18:18: fatal error: zlib.h: No such file or directory
compilation terminated.
make[4]: *** [CMakeFiles/ale-c-lib.dir/build.make:189: CMakeFiles/ale-c-lib.dir/src/common/ScreenExporter.cpp.obj] Error 1
make[4]: Leaving directory '/D/Programming/Py_script/openai_gym/atari-py/atari_py/ale_interface/build'
make[3]: *** [CMakeFiles/Makefile2:68: CMakeFiles/ale-c-lib.dir/all] Error 2
make[3]: Leaving directory '/D/Programming/Py_script/openai_gym/atari-py/atari_py/ale_interface/build'
make[2]: *** [Makefile:84: all] Error 2
make[2]: Leaving directory '/D/Programming/Py_script/openai_gym/atari-py/atari_py/ale_interface/build'
make[1]: *** [Makefile:4: build] Error 2
make[1]: Leaving directory '/D/Programming/Py_script/openai_gym/atari-py/atari_py/ale_interface'
make: *** [Makefile:4: build] Error 2
""

**Comment by Red-Pheonix** [comment]
Never mind, I solved my problem. I edited the CMAKE file to include the zlib source folder and it compiled perfectly. Perhaps it would be better if the cmake file searched for zlib or something along those lines?

**Comment by christopherhesse** [comment]
This looks like a failure of atari-py to build on windows, closing in favor of https://github.com/openai/atari-py/issues/5
