### ISSUE TITLE
How to get the detailed info of env?

### ISSUE THREAD

**Issue by inksci** [openai/gym#758]
For example, the env 'Pendulum-v0', I can print its observation, action with python:
```
observation: [ 0.452032    0.89200172  0.91324294]
action: [ 0.19525402]
```
BUT what are the meaning of these data? What they represent for?
Any information is welcome!

**Comment by FirefoxMetzger** [comment]
The meaning of the observation is unique to each environment and is not further specified by the gym framework. So where to get the info depends on the individual environment.
The `info` field might be useful for additional information, though I find it's rarely used.

Some environments are documented in this repo's wiki. If the environment comes from outside of gym, check their docs.
Otherwise your out of luck and have to stick to reading the source code, google and perhaps a lucky blog post. But don't worry, it's python and the API isn't to complex so it should be fairly straight forward.

**Comment by inksci** [comment]
@FirefoxMetzger 
Thank for your answer, which is helpful.
Moreover, if there is a web page introducing all the information of env within gym, the people who use gym will feel easier for their work.

**Comment by ImpulseAdventure** [comment]
In the case of *Pendulum-v0* you can find some details on the observation and action spaces here:
https://github.com/openai/gym/wiki/Pendulum-v0

**Comment by madvn** [comment]
#106

**Comment by madvn** [comment]
See #106

**Comment by inksci** [comment]
@ImpulseAdventure That is the perfect example what I want.

**Comment by christopherhesse** [comment]
Thanks for answering this @ImpulseAdventure, this is not documented for most environments, though you can often figure out from the code what the observations and actions are.
