### ISSUE TITLE
README getting-started needs significant work

### ISSUE THREAD

**Issue by justinTM** [openai/gym#814]
As a 3rd year student in CS who has at least basic experience with command line Python scripts, reading through the Installation/getting-started section had me scratching my head for about an hour just trying to get set up; even found myself with multiple tabs open from StackOverflow trying to find answers to the installation problems!

Considering this repo seems to be geared towards getting beginners started with Reinforcement Learning/Machine Learning/AI, I'm proposing we go through the getting-started section and add more helpful bits for newcomers to get this software running. Namely, the folder structure, which scripts to run, how to run them, what errors to expect when running on certain platforms.

For example, the dependency `six` is basically broken with Python in macOS, requiring some non-trivial workarounds. We could add a little blurb about this and point them to one of the Github issue comments to solve it. 

Another example would be adding a "how to run examples", with a line of code a user can copy-paste and get started. All of the example scripts are lines of Python code, but existing scripts can actually be run from the command line; it might help to (better) tell users these exist, and how to run  them :)

I'm prepared for "we assume basic knowledge...", "users should know how to do...", etc. but honestly if a CS student with Python experience--like myself-- had difficulties, it saddens me to imagine someone with no CS background or Python experience trying to read through this documentation :/

**Comment by FirefoxMetzger** [comment]
I'm no MacOS user, so I can't comment much on `six` dependency issues. However, I think that any issues with `six`, including dependencies on mac should be discussed in the `six` repo; Not here. That way they can be solved upstream and propagated to downstream projects, including `gym`.
It would be a nightmare to maintain such references in this projects README, as they would require constant updates depending on changes in another repo. However, I can't see much harm in adding an issue to this repo with the references you mentioned. Those who need it will value the input and it cuts down search time until the issue is solved upstream.

Personally, I think the best way to learn how to use a library is to look at code that uses the library. Copy-pasting one-liners into a CLI and watching an agent train doesn't tell you much about whats under the hood. However, I agree that the examples could use more documentation. How about adding a `README.md` to the example folder?

Yes, there are friendlier projects to pick up, but then again the audience for `gym` is not as big as it is with say `keras`. Add to that the fact that many people here are more interested in RL research rather then devops and you can see where the lack of documentation comes from (building new functionality is cool ... documenting it not so much =D ). 
That said, if you have the time, please feel free to add to the existing documentation and submit a PR, I'll happily review it and then we can go pester the OpenAI folks to get it merged.
