### ISSUE TITLE
Mujoco-py version degrade

### ISSUE THREAD

**Issue by Shaofanl** [openai/gym#823]
I installed mujoco-py1.5.1 manually. And when I run `sudo pip3 install -e '.[mujoco]', it automatically degrade to mujoco-py-0.5.7. What should I do if I want to use mujoco-py-1.5.1?

**Comment by khoa-ngo** [comment]
Hi Shaofanl,

Support for Mujoco 1.5 had been recently added, check it out [here](https://github.com/openai/gym/pull/834).

Make sure you fetched the latest gym, have mujoco 1.5.1 installed, and have the mjpro150 folder in the appropriate location: [installation instruction here](https://github.com/openai/mujoco-py/blob/master/README.md), [download link here](https://www.roboti.us/index.html).

Then try the following to see if it works:

import gym
env = gym.make('Reacher-v2')
env.reset()
for _ in range(1000):
    env.render()
    env.step(env.action_space.sample()) # take a random action

**Comment by Shaofanl** [comment]
Thanks! Also I want to know whether the mujoco-py 1.5.1 is compatible with mujoco-py 0.5.7. Are there some major changes that will not raise exceptions but might act differently between two versions?

**Comment by khoa-ngo** [comment]
I've not exactly sure, I think there had been significant changes from 0.5.7 to 1.5.5. [matthiasplappert](https://github.com/matthiasplappert) ran some benchmark [here](https://github.com/openai/gym/pull/834) with mujoco-1.5.1, comparing it against 0.5.7, and it looks stable.

He also bumped the environment versions. So you you have to do: env = gym.make('Humanoid-v2') instead of env = gym.make('Humanoid-v1'). The following should run for you:

`import gym
env = gym.make('Humanoid-v2')
env.reset()

for _ in range(1000):
    env.render()
    env.step(env.action_space.sample())`
