### ISSUE TITLE
Help with Request for Research: Transfer Learning Between Different Games via Generative Models

### ISSUE THREAD

**Issue by ahsteven** [openai/gym#935]
I am just getting started with gym and was wondering if there was already code available to say load a pretrained agent and generate 10000 trajectories of the expert playing a game? If not what would the recommended way of saving such data be?

How was the data generated for the GAIL baseline?

Any suggestions in getting started with this would be greatly appreciated.

**Comment by Kelym** [comment]
OpenAI Roboschool has a few pretrained agent: https://github.com/openai/roboschool/tree/master/agent_zoo
Otherwise try OpenAI baseline to train? 

I am sure you could find more help using [OpenAI gym forum](https://discuss.openai.com/). Not sure if it is appropriate to post this kind of question as an open issue ...

**Comment by ahsteven** [comment]
Thanks for sharing the info.
