### ISSUE TITLE
Why do env.step return reward 0 even for the terminal state? (i.e game over) 

### ISSUE THREAD

**Issue by NileshPS** [openai/gym#945]
Forgive me if I am wrong ;-). As i understand,  we need to give a negative reward for terminal / game over state so the agent can figure out that it's in an unfavourable state. In Breakout, every step which does not take out a brick (or block) will  reward 0 points. Same happens when we lose a life (or 5 lives too). My intuition tells me it should be  <= -1.  
Why is it like that?

**Comment by mashoujiang** [comment]
I meet the same problem..unsolved.

**Comment by AkashGanesan** [comment]
I think it may actually make sense to have a function of the env if we are in the terminal state.  Of course, we can always take a step and then see it is a terminal state and be done with it.

**Comment by christopherhesse** [comment]
If you want to shape the rewards your agent receives to penalize game over, that can be done with an environment wrapper.  You're giving your agent more information about the task than just the default reward signal does.

A Breakout agent should still be able to (in theory) get the maximum possible score without this penalty since maximizing total reward should take into account that the agent must survive in order to do so.  Of course, this means that the agent doesn't mind losing a life since there's no penalty, but that's sort of how the score based reward is setup.
