### ISSUE TITLE
VideoRecorder error running random_agent.py

### ISSUE THREAD

**Issue by kirk86** [openai/gym#948]
Hi I keep getting the following error after running `random_agent.py` script:

````
python random_agent.py
INFO: Making new env: CartPole-v0
WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
INFO: Creating monitor directory /tmp/random-agent-results
INFO: Starting new video recorder writing to /tmp/random-agent-results/openaigym.video.0.8775.video000000.mp4
DEBUG: Capturing video frame: path=/tmp/random-agent-results/openaigym.video.0.8775.video000000.mp4
DEBUG: Starting ffmpeg with "ffmpeg -nostats -loglevel error -y -r 50 -f rawvideo -s:v 600x400 -pix_fmt rgb24 -i - -vcodec libx264 -pix_fmt yuv420p /tmp/random-agent-results/openaigym.video.0.8775.video000000.mp4"
Unknown encoder 'libx264'
DEBUG: Capturing video frame: path=/tmp/random-agent-results/openaigym.video.0.8775.video000000.mp4
Traceback (most recent call last):
  File "random_agent.py", line 43, in <module>
    ob, reward, done, _ = env.step(action)
  File "/home/user/miniconda3/envs/tf/lib/python3.6/site-packages/gym/wrappers/monitor.py", line 32, in step
    done = self._after_step(observation, reward, done, info)
  File "/home/user/miniconda3/envs/tf/lib/python3.6/site-packages/gym/wrappers/monitor.py", line 179, in _after_step
    self.video_recorder.capture_frame()
  File "/home/user/miniconda3/envs/tf/lib/python3.6/site-packages/gym/wrappers/monitoring/video_recorder.py", line 116, in capture_frame
    self._encode_image_frame(frame)
  File "/home/user/miniconda3/envs/tf/lib/python3.6/site-packages/gym/wrappers/monitoring/video_recorder.py", line 166, in _encode_image_frame
    self.encoder.capture_frame(frame)
  File "/home/user/miniconda3/envs/tf/lib/python3.6/site-packages/gym/wrappers/monitoring/video_recorder.py", line 301, in capture_frame
    self.proc.stdin.write(frame.tobytes())
BrokenPipeError: [Errno 32] Broken pipe
DEBUG: Closing video encoder: path=/tmp/random-agent-results/openaigym.video.0.8775.video000000.mp4
ERROR: VideoRecorder encoder exited with status 1
DEBUG: Writing training manifest file to /tmp/random-agent-results/openaigym.manifest.0.8775.manifest.json
INFO: Finished writing results. You can upload them to the scoreboard via gym.upload('/tmp/random-agent-results')
Exception ignored in: <bound method Viewer.__del__ of <gym.envs.classic_control.rendering.Viewer object at 0x7f72c083a470>>
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/tf/lib/python3.6/site-packages/gym/envs/classic_control/rendering.py", line 143, in __del__
  File "/home/user/miniconda3/envs/tf/lib/python3.6/site-packages/gym/envs/classic_control/rendering.py", line 62, in close
  File "/home/user/miniconda3/envs/tf/lib/python3.6/site-packages/pyglet/window/xlib/__init__.py", line 480, in close
  File "/home/user/miniconda3/envs/tf/lib/python3.6/site-packages/pyglet/gl/xlib.py", line 345, in destroy
  File "/home/user/miniconda3/envs/tf/lib/python3.6/site-packages/pyglet/gl/base.py", line 334, in destroy
  File "/home/user/miniconda3/envs/tf/lib/python3.6/site-packages/pyglet/gl/xlib.py", line 335, in detach
  File "/home/user/miniconda3/envs/tf/lib/python3.6/site-packages/pyglet/gl/lib.py", line 97, in errcheck
ImportError: sys.meta_path is None, Python is likely shutting down
```

**Comment by DanielsCode** [comment]
I have the same issue. Any hints?

**Comment by kirk86** [comment]
Nope basically I gave up but people have said that if you install python=3.5.2 then probably most of the things will work out of the box. Personally I'm waiting support for 3.6.x

**Comment by DanielsCode** [comment]
Thanks for your hint. I tried it also with 3.5.2 - with no further success.

**Comment by kirk86** [comment]
@DanielsCode there's also another option which is to use gym version=0.9.x alongside with mujoco version 1.3 python 2.7.x. Then remember to use from the examples for instance `humanoid-v1` and not `humannoid-v2`. Others have reported that for them it worked. Dunno, maybe give it a try.

**Comment by coderrg** [comment]
I am experiencing the same issue. Has anyone found a solution?

**Comment by fantaa499** [comment]
> I am experiencing the same issue. Has anyone found a solution?
try this:
`conda install -c conda-forge ffmpeg`

[https://github.com/duckietown/gym-duckietown/blob/master/README.md#unknown-encoder-libx264-when-using-gymwrappersmonitor](url)

**Comment by coderrg** [comment]
Thank you for the response! Unfortunately, the problem seems to be persisting.

**Comment by olivernina** [comment]
I had the same problem and it seemed to go away by removing the ffmpeg installed on anaconda with conda remove ffmpeg and then build ffmpeg on the system following these instructions: 
https://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu
Good luck!

**Comment by algebraic-mouse** [comment]
Hi, I know this doesn't solve the problem, but I used a screen recorder as a work-around. (E.g. powerpoint, quicktime player screen recording) Hope this helps you move along.

**Comment by christopherhesse** [comment]
It looks like https://github.com/openai/gym/blob/master/gym/wrappers/monitoring/video_recorder.py depends on some `ffmpeg` features.  It's likely that this should use `imageio` along with `imageio-ffmpeg` to get consistent results across multiple platforms which may or may not have the correct `ffmpeg` installed.

**Comment by christopherhesse** [comment]
Closing this in favor of https://github.com/openai/gym/issues/1470 for now people should use @fantaa499's workaround

**Comment by alimurreza** [comment]
> ffmpeg

It worked :). Thanks a lot

**Comment by alimurreza** [comment]
> > I am experiencing the same issue. Has anyone found a solution?
> 
> try this:
> `conda install -c conda-forge ffmpeg`
> 
> for more [information](https://github.com/duckietown/gym-duckietown/blob/master/README.md#unknown-encoder-libx264-when-using-gymwrappersmonitor)

It worked :). Thanks a lot for saving time and effort.

**Comment by NoahDaNerd** [comment]
Has anyone figured this out? (tdtce's solution didn't work)

**Comment by vwxyzjn** [comment]
Hey @NoahDaNerd I just had this issue building docker containers. Looks like the newest version of `ffmpeg==4.3.0` breaks things and downgrading solves the issue. Specifically, `conda install -c conda-forge ffmpeg==4.2.2` solves my issue.

**Comment by ChenControl** [comment]
Here I would like to share the install memo to Install openAI and run pytest.

https://github.com/openai/baselines
Ubuntu
sudo apt-get update && sudo apt-get install cmake libopenmpi-dev python3-dev zlib1g-dev

mkdir OpenAI
	install 
	https://pypi.org/project/PyQtWebEngine/#files
	install PyQt5 5.13.0
	https://pypi.org/project/PyQt5/5.13.0/#files
	pip install PyQt5==5.13.0
cd ./OpenAI/
cd ./baselines-master/
=============================precondition pre-requirement==============
You had better install env with python 3.6 and then install tensorflow15.5 to run

sudo apt-get install python3-virtualenv
virtualenv -p /usr/bin/python3.6 venv
source ./activate
pip install tensorflow-gpu==1.15.5     (the highest version below 2.0)
------------------
sudo apt install linuxbrew-wrapper && brew update
It need special treatment to install brew as following:
https://www.how2shout.com/linux/how-to-install-brew-ubuntu-20-04-lts-linux/
sudo apt update
sudo apt-get install build-essential
sudo apt install git -y
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> /home/username/.profile
brew doctor
---------------------
brew install libav
sudo apt-get install libav-tools
pip install filelock==3.0.0
pip install atari_py
pip install gym
pip install gym[atari]
pip install pandas 
pip install matplotlib
apt-get install -y libglu1-mesa-dev libgl1-mesa-dev libosmesa6-dev xvfb ffmpeg curl patchelf libglfw3 libglfw3-dev cmake zlib1g zlib1g-dev swig
ffmpeg problem could be solved by following instruction: I skip some library due to stability concern, waiting for the stable version.20211207

https://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu
sudo apt-get update -qq && sudo apt-get -y install autoconf   automake   build-essential   cmake   git-core   libass-dev   libfreetype6-dev   libgnutls28-dev   libmp3lame-dev   libsdl2-dev   libtool   libva-dev   libvdpau-dev   libvorbis-dev   libxcb1-dev   libxcb-shm0-dev   libxcb-xfixes0-dev  meson   ninja-build   pkg-config   texinfo   wget   yasm  zlib1g-dev
On Ubuntu 20.04 you may also need this command
sudo apt install libunistring-dev libaom-dev libdav1d-dev
sudo apt-get install nasm
sudo apt-get install libx264-dev
sudo apt-get install libvpx-dev
sudo apt-get install libx265-dev libnuma-dev
sudo apt-get install libfdk-aac-dev
sudo apt-get install libopus-dev
sudo apt-get install libunistring-dev
sudo apt install snapd
sudo snap install dav1d
	there is someproblem instal dav1d, download the source code, and compile by yourself.Follow the readme in the sourcecode.
https://www.videolan.org/projects/dav1d.html
 1. Install [Meson](https://mesonbuild.com/) (0.47 or higher), [Ninja](https://ninja-build.org/), and, for x86\* targets, [nasm](https://nasm.us/) (2.14 or higher)
2. Run `mkdir build && cd build` to create a build directory and enter it
3. Run `meson ..` to configure meson, add `--default-library=static` if static linking is desired
4. Run `ninja` to compile
The following line solve the video problem finally, pay attention to the 4.2.2 version No.. 
pytest shows 94 pass, 32 skipped, 31 warning in 392.73s
conda install -c conda-forge ffmpeg==4.2.2

————————————————
sudo apt-get update && sudo apt-get install cmake libopenmpi-dev python3-dev zlib1g-dev
pip install -e .
pip install ./PyQt5-5.13.0-5.13.0-cp35.cp36.cp37.cp38-abi3-manylinux1_x86_64.whl 
pip install PyQtWebEngine==5.12.1
cd ./baselines-master/
pip install -e .
Install video player
pip install python-vlc
sudo apt install ffmpeg

============
run the pytest
=============
pip install pytest
pytest
