### ISSUE TITLE
Directory '.' is not installable. File 'setup.py' not found.

### ISSUE THREAD

**Issue by chrisspen** [openai/gym#974]
The README instructs people to install via pip like:

    pip install -e '.[classic_control]'

or:

    pip install -e 'gym[classic_control]'

But this is not a valid pip command:

    $ cd /tmp
    $ mkdir gym
    $ cd gym
    $ virtualenv .env
    New python executable in /tmp/gym/.env/bin/python
    Installing setuptools, pip, wheel...done.
    $ . .env/bin/activate
    $ pip --version
    pip 9.0.3 from /tmp/gym/.env/local/lib/python2.7/site-packages (python 2.7)
    $ pip install -e 'gym[classic_control]'
    Directory '.' is not installable. File 'setup.py' not found.

Are the instructions implying you're installing from inside a cloned git repo? If so, that's a very unusual way to install Python packages, especially when using pip.

**Comment by trane293** [comment]
> Are the instructions implying you're installing from inside a cloned git repo? If so, that's a very unusual way to install Python packages, especially when using pip.

Yes, that's exactly how it's supposed to be. I agree it's kind of error prone, but not at all unusual. Just 
```
cd $HOME
git clone https://github.com/openai/gym.git
cd gym
virtualenv venv
source ./venv/bin/activate
pip install -e .[classic_control]
```

**Comment by chrisspen** [comment]
Ok. Thanks for the clarification.

**Comment by KhyatiA** [comment]
This does not work for me. And even after executing the commands, as mentioned above, I get the error : `ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: /home/aaitech1/PycharmProjects/FalconIntegrationTest
`
Shared screenshot of it below : 
![Screenshot from 2021-01-14 03-49-28](https://user-images.githubusercontent.com/23726115/104517169-8e833000-561b-11eb-9dc2-3936d87f91e8.png)

**Comment by Ashish0628** [comment]
Please share the solution, if you got it

**Comment by saadziasheikh** [comment]
Is there any solution to this?

**Comment by pseudo-rnd-thoughts** [comment]
Your current directory needs to contain the Gym repo. I suspect that your directory does not contain the repo with setup.py in it

**Comment by theredpea** [comment]
For me the project ([arelle](https://github.com/Arelle/Arelle)) does not have a setup.py file.  That's because arelle uses [`pyproject.toml` file instead](https://stackoverflow.com/questions/62983756/what-is-pyproject-toml-file-for).  

So I expected setup.py would not be found: "File 'setup.py' not found." **But I didn't know why `pip` couldn't use `pyproject.toml` instead.**

I learned from [a StackOverflow comment](https://stackoverflow.com/questions/69711606/how-to-install-a-package-using-pip-in-editable-mode-with-pyproject-toml#comment126329840_69711730)  that "Pip supports editable installs from pyproject.toml files since [21.3](https://pip.pypa.io/en/stable/news/#v21-3)

 > Support editable installs for projects that have a pyproject.toml and use a build backend that supports [PEP 660](https://peps.python.org/pep-0660/). ([#8212](https://github.com/pypa/pip/issues/8212))

My pip is version 18.1, so that's probably the reason:
```
$ pip --version
pip 18.1 from C:\ProgramData\Anaconda3\lib\site-packages\pip (python 3.7)
```

I'll upgrade my pip and try again... Yes, I [upgraded pip](https://pip.pypa.io/en/stable/installation/#upgrading-pip) ...

```
$ python -m pip install --upgrade pip
$ pip --version
pip 23.0.1 from c:\programdata\anaconda3\lib\site-packages\pip (python 3.7)
```

and now I could do this workflow:

```
$ git clone https://github.com/Arelle/Arelle.git
$ cd arelle
$ pip install -e .
```

(Maybe I could've used the shortcut recommended on the arelle project:  `pip install git+https://git@github.com/arelle/arelle.git@master` This method failed for me the first time (because "File could not be found!", presumably because of an old version of pip!)
