### ISSUE TITLE
How to implement a timer for a certain action in step()

### ISSUE THREAD

**Issue by Rokas98765** [openai/gym#986]
One of the actions I want the agent to do needs to have a delay between every action. For context, in pygame I have the following code for shooting a bullet:

        if keys[pygame.K_SPACE]:
            current_time = pygame.time.get_ticks()
            # ready to fire when 600 ms have passed.
            if current_time - previous_time > 600:
                previous_time = current_time
                bullets.append([x + 25, y + 24])

I've set a timer to prevent bullet spamming, how would I construct this to work with the step() method? My other actions are moving up, down, left, right. 

This is my first time creating a project with OpenAI-gym so I'm not sure what the capabilities of the toolkit are, any help would be greatly appreciated.

**Comment by christopherhesse** [comment]
So time would work, but you should use your own fake time instead of the system clock.  Just start with time = 0 at the start and each time step is called, increment by 1/30 or whatever your framerate is.  You can then do the same time comparison.  Or you can keep track of steps and use that as a unit instead.
